### ISSUE TITLE
Crash when third external command in a pipe throws exception

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#1036]
```
[~]─> elvish -buildinfo
Version: v0.13-371-g2d86a245
Go version: go1.14.2
Reproducible build: true
```

Elvish seems to crash when the third-or-later command in a pipeline throws an exception. See example with full panic trace below.

Some notes:

- Any exception in the third or later command produces the crash, not only nonexisting commands, for example `false`, `grep` (without arguments), etc.
- It seems to happen if the third *external command* in the pipeline fails. If there are built-ins in the pipeline, those don't count.

```
[~]─> ls -l | wc -l | foo

goroutine 1 [running]:
github.com/elves/elvish/pkg/sys.DumpStack(0xc00042f238, 0x14e2b40)
	github.com/elves/elvish/pkg/sys/dumpstack.go:10 +0x9d
github.com/elves/elvish/pkg/shell.rescue()
	github.com/elves/elvish/pkg/shell/shell.go:100 +0x7d
panic(0x14e2b40, 0x198cd30)
	runtime/panic.go:969 +0x166
github.com/elves/elvish/pkg/eval.(*Exception).Show(0xc0006188e0, 0x1572058, 0x2, 0x1572058, 0x2)
	github.com/elves/elvish/pkg/eval/exception.go:60 +0x5f1
github.com/elves/elvish/pkg/eval.(*Exception).Show(0xc0003028e0, 0x0, 0x0, 0xbd4dd60, 0xc0003028e0)
	github.com/elves/elvish/pkg/eval/exception.go:80 +0x44a
github.com/elves/elvish/pkg/diag.ShowError(0x162e8a0, 0xc000010020, 0x162e0c0, 0xc0003028e0)
	github.com/elves/elvish/pkg/diag/show_error.go:12 +0x72
github.com/elves/elvish/pkg/shell.Interact(0xc000010010, 0xc000010018, 0xc000010020, 0xc00017bca0)
	github.com/elves/elvish/pkg/shell/interact.go:90 +0xa05
github.com/elves/elvish/pkg/shell.program.Run(0xc000010010, 0xc000010018, 0xc000010020, 0xc0000f6000, 0xc0000201b0, 0x0, 0x0, 0x19c8500, 0xc00017bf68)
	github.com/elves/elvish/pkg/shell/shell.go:40 +0x2bc
github.com/elves/elvish/pkg/prog.Run(0xc000010010, 0xc000010018, 0xc000010020, 0xc0000201b0, 0x1, 0x1, 0xc00017bf48, 0x3, 0x3, 0x0)
	github.com/elves/elvish/pkg/prog/prog.go:134 +0x2a2
main.main()
	github.com/elves/elvish/main.go:17 +0x11f

goroutine 18 [chan receive, 2 minutes]:
github.com/elves/elvish/pkg/eval.getBlackholeChan.func1(0xc0000c4060)
	github.com/elves/elvish/pkg/eval/port.go:59 +0x47
created by github.com/elves/elvish/pkg/eval.getBlackholeChan
	github.com/elves/elvish/pkg/eval/port.go:58 +0x58

goroutine 20 [syscall]:
os/signal.signal_recv(0x1635240)
	runtime/sigqueue.go:144 +0x96
os/signal.loop()
	os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
	os/signal/signal.go:127 +0x44

goroutine 22 [chan receive]:
github.com/elves/elvish/pkg/shell.setupShell.func1(0xc0000c40c0, 0xc000010010, 0xc000010018, 0xc000010020)
	github.com/elves/elvish/pkg/shell/shell.go:52 +0xc8
created by github.com/elves/elvish/pkg/shell.setupShell
	github.com/elves/elvish/pkg/shell/shell.go:51 +0x12d

goroutine 23 [chan receive]:
github.com/elves/elvish/pkg/cli/prompt.(*Prompt).loop(0xc0000f37a0)
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:77 +0xc8
created by github.com/elves/elvish/pkg/cli/prompt.New
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:70 +0x15f

goroutine 24 [chan receive]:
github.com/elves/elvish/pkg/cli/prompt.(*Prompt).loop(0xc0000f3880)
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:77 +0xc8
created by github.com/elves/elvish/pkg/cli/prompt.New
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:70 +0x15f

goroutine 11008 [syscall, 2 minutes]:
syscall.syscall6(0x107ddb0, 0x13c, 0xc000c07a9c, 0x0, 0xc000bb4000, 0x0, 0x0, 0x0, 0x0, 0x0)
	runtime/sys_darwin.go:74 +0x2e
syscall.wait4(0x13c, 0xc000c07a9c, 0x0, 0xc000bb4000, 0x90, 0x1561aa0, 0x1)
	syscall/zsyscall_darwin_amd64.go:44 +0x87
syscall.Wait4(0x13c, 0xc000c07aec, 0x0, 0xc000bb4000, 0x39, 0xc0002c9b00, 0x6)
	syscall/syscall_bsd.go:129 +0x51
os.(*Process).wait(0xc0006d8000, 0x39, 0xc0002c9b00, 0x6)
	os/exec_unix.go:38 +0x7b
os.(*Process).Wait(...)
	os/exec.go:125
github.com/elves/elvish/pkg/eval.ExternalCmd.Call(0xc0000a4f00, 0x39, 0xc000a962a0, 0xc000996000, 0x5, 0x8, 0xc0001feae0, 0xc0003f1800, 0xc00002a050)
	github.com/elves/elvish/pkg/eval/external_cmd.go:91 +0x37e
github.com/elves/elvish/pkg/eval.(*formOp).invoke(0xc00069d6c0, 0xc000a962a0, 0x0, 0x0)
	github.com/elves/elvish/pkg/eval/compile_effect.go:388 +0x8be
github.com/elves/elvish/pkg/eval.effectOp.exec(0x162e200, 0xc00069d6c0, 0xe93, 0x1003, 0xc000a962a0, 0xffffffffffffffff, 0xffffffffffffffff)
	github.com/elves/elvish/pkg/eval/op.go:33 +0x69
github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke.func1(0x162e200, 0xc00069d6c0, 0xe93, 0x1003, 0xc000a962a0, 0xc0006b2060, 0xc00028e5c0, 0xc000705600)
	github.com/elves/elvish/pkg/eval/compile_effect.go:144 +0x60
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke
	github.com/elves/elvish/pkg/eval/compile_effect.go:143 +0x23e

goroutine 11009 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc00028e5c8)
	runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc00028e5c0)
	sync/waitgroup.go:130 +0x64
github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke.func2(0xc00028e5c0, 0xc000a96230, 0xc0002977a0, 0xc0006b2060, 0x1, 0x1)
	github.com/elves/elvish/pkg/eval/compile_effect.go:164 +0x40
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke
	github.com/elves/elvish/pkg/eval/compile_effect.go:163 +0x2b4

runtime error: invalid memory address or nil pointer dereference

Execing recovery shell /bin/sh

```

**Comment by krader1961** [comment]
Duplicate of #1014 which itself is probably a duplicate of #994.

**Comment by krader1961** [comment]
FYI, commit c5c07bbb fixes this issue so it can be closed.

**Comment by krader1961** [comment]
@zzamboni, Is this still an issue for you? AFAICT this has been fixed and the issue closed.

**Comment by zzamboni** [comment]
Yes, this has been fixed.
