### ISSUE TITLE
panic on show $ok

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1064]
Running `show $ok` results in a panic:

```
⬥ elvish --version
v0.14.0-rc1-3-gb310b4fb
⬥ elvish
⬥ show $ok
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7f3f83]

goroutine 1092 [running]:
github.com/elves/elvish/pkg/eval.(*Exception).Show(0xdb3090, 0x0, 0x0, 0x8ff8a0, 0x8ff8a0)
	/opt/pkg/gopkg/src/github.com/elves/elvish/pkg/eval/exception.go:64 +0x143
github.com/elves/elvish/pkg/eval.show(0xc0002b0540, 0x7f24ee158a58, 0xdb3090)
	/opt/pkg/gopkg/src/github.com/elves/elvish/pkg/eval/builtin_fn_io.go:505 +0x7a
reflect.Value.call(0x8d61c0, 0x9bc398, 0x13, 0x9926cf, 0x4, 0xc000223f80, 0x2, 0x2, 0x2, 0x18, ...)
	/opt/pkg/pkg/go-1.13.7/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x8d61c0, 0x9bc398, 0x13, 0xc000223f80, 0x2, 0x2, 0x1, 0x2, 0x40c326)
	/opt/pkg/pkg/go-1.13.7/src/reflect/value.go:321 +0xb4
github.com/elves/elvish/pkg/eval.(*GoFn).Call(0xc00013da40, 0xc0002b0540, 0xc0000fd7b0, 0x1, 0x1, 0xc000223f50, 0x0, 0x1)
	/opt/pkg/gopkg/src/github.com/elves/elvish/pkg/eval/go_fn.go:235 +0x638
github.com/elves/elvish/pkg/eval.(*formOp).invoke(0xc0002396c0, 0xc0002b0540, 0x0, 0x0)
	/opt/pkg/gopkg/src/github.com/elves/elvish/pkg/eval/compile_effect.go:388 +0x95d
github.com/elves/elvish/pkg/eval.effectOp.exec(0xa48b80, 0xc0002396c0, 0x0, 0x8, 0xc0002b0540, 0xc000096f60, 0xc0000801e0)
	/opt/pkg/gopkg/src/github.com/elves/elvish/pkg/eval/op.go:33 +0x69
github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke.func1(0xa48b80, 0xc0002396c0, 0x0, 0x8, 0xc0002b0540, 0xc000114280, 0xc000109190, 0xc000353c00)
	/opt/pkg/gopkg/src/github.com/elves/elvish/pkg/eval/compile_effect.go:144 +0x60
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke
	/opt/pkg/gopkg/src/github.com/elves/elvish/pkg/eval/compile_effect.go:143 +0x23e
Exception: elvish exited with 2
[tty 2], line 1: elvish
```

**Comment by zzamboni** [comment]
Can confirm.
