### ISSUE TITLE
Panic happens when using `put` in a backgrounded function

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1069]
I was playing around while exploring job notification behavior (see #1067) and noticed the following causes a panic:

```elvish
> fn wtf { sleep 1; put yes }
> wtf &
goroutine 51514 [running]:
github.com/elves/elvish/pkg/eval.put(0xc0008167e0, 0xc0005ed5a0, 0x1, 0x1)
	/Users/krader/projects/3rd-party/elvish/pkg/eval/builtin_fn_io.go:389 +0x93
reflect.Value.call(0x14c6a60, 0x15a2da0, 0x13, 0x1578edc, 0x4, 0xc000a032c0, 0x2, 0x2, 0x2, 0x18, .)
	/usr/local/Cellar/go/1.14.3/libexec/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x14c6a60, 0x15a2da0, 0x13, 0xc000a032c0, 0x2, 0x2, 0x1, 0x2, 0x100e846)
	/usr/local/Cellar/go/1.14.3/libexec/src/reflect/value.go:321 +0xb4
github.com/elves/elvish/pkg/eval.(*GoFn).Call(0xc0001357a0, 0xc0008167e0, 0xc0005ed560, 0x1, 0x1, 0)
	/Users/krader/projects/3rd-party/elvish/pkg/eval/go_fn.go:235 +0x638
github.com/elves/elvish/pkg/eval.(*formOp).invoke(0xc000a32680, 0xc0008167e0, 0x0, 0x0)
	/Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:388 +0x8be
github.com/elves/elvish/pkg/eval.effectOp.exec(0x1635140, 0xc000a32680, 0x13, 0x1b, 0xc0008167e0, 0)
	/Users/krader/projects/3rd-party/elvish/pkg/eval/op.go:33 +0x69
github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke.func1(0x1635140, 0xc000a32680, 0x13, 0x1b, 0x)
	/Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:144 +0x60
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke
	/Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:143 +0x23e
```

Note that using `echo` or `print` does not cause a panic and the word "yes" is written to the tty.

**Comment by krader1961** [comment]
Obviously this issue applies to any builtin or Elvish function that writes to the value channel -- not just the `put` builtin. It does not apply to external commands since they cannot write to the value channel. We could continue to allow, and document, the current behavior. Another option is to implicitly convert any value channel output from a backgrounded builtin (or function) to byte value output as if the invocation was `wtf | to-lines &`. This works today:

```
> { echo yes; put no; echo wtf } | to-lines &
yes
wtf
no
job { echo yes; put no; echo wtf } | to-lines & finished
```

Whereas the same thing without piping through `to-lines` results in a panic:

```
> { echo yes; put no; echo wtf } &
yes
panic: send on closed channel
```

Elvish tries to avoid panics other than for scenarios beyond its control. It seems like that policy should apply to this scenario.

**Comment by krader1961** [comment]
Somewhere along the line a change was made that fixed this issue.
