### ISSUE TITLE
Panic: interface conversion: eval.fnWrap is not diag.Ranger: missing method Range

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#1126]
I started getting the following panice when using the [git](https://github.com/zzamboni/elvish-completions/blob/master/git.elv) completion module, and trying to complete the `git push` command. The panic occurs when I press `Tab` after `git push `.

I have not investigated yet, but putting this here in case someone has an idea what recent change could have caused it:

```
> git push panic: interface conversion: eval.fnWrap is not diag.Ranger: missing method Range

goroutine 23569 [running]:
github.com/elves/elvish/pkg/eval.closureFields.Body(0xc0004d8140, 0x0, 0x0)
	github.com/elves/elvish/pkg/eval/closure.go:141 +0x48
reflect.Value.call(0x1480ce0, 0xc0004d8140, 0x613, 0x14a4d5c, 0x4, 0x0, 0x0, 0x0, 0x8, 0xc000217688, ...)
	reflect/value.go:475 +0x8c7
reflect.Value.Call(0x1480ce0, 0xc0004d8140, 0x613, 0x0, 0x0, 0x0, 0x613, 0x1, 0x1)
	reflect/value.go:336 +0xb9
github.com/elves/elvish/pkg/eval/vals.(*structMapIterator).Get(0xc0002177d0, 0x1480ce0, 0xc0004d8140, 0x19, 0xc001107290, 0x9, 0x1481b20, 0x17)
	github.com/elves/elvish/pkg/eval/vals/struct_map.go:117 +0xc9
github.com/elves/elvish/pkg/eval/vals.indexStructMap(0x1529e20, 0xc0004d8140, 0x140ac60, 0xc000327050, 0xc0004d8140, 0x1, 0xc000ba4870, 0x104e)
	github.com/elves/elvish/pkg/eval/vals/index.go:88 +0x287
github.com/elves/elvish/pkg/eval/vals.Index(0x145bb00, 0xc0004d8140, 0x140ac60, 0xc000327050, 0x1, 0x0, 0x0, 0x14340a0)
	github.com/elves/elvish/pkg/eval/vals/index.go:58 +0x33e
github.com/elves/elvish/pkg/eval.(*indexingOp).exec(0xc0003835c0, 0xc000c6ab60, 0xc000ba4ac0, 0x1348f69, 0x140d080, 0xc0004a3780, 0xc0001cc8c0)
	github.com/elves/elvish/pkg/eval/compile_value.go:245 +0x298
github.com/elves/elvish/pkg/eval.compoundOp.exec(0x724, 0x733, 0x0, 0xc000327010, 0x1, 0x1, 0xc000c6ab60, 0x0, 0x1000, 0x101020a, ...)
	github.com/elves/elvish/pkg/eval/compile_value.go:73 +0x69
github.com/elves/elvish/pkg/eval.(*formOp).exec(0xc00032aa50, 0xc000c6ab60, 0x0, 0x0)
	github.com/elves/elvish/pkg/eval/compile_effect.go:359 +0xacb
github.com/elves/elvish/pkg/eval.(*pipelineOp).exec.func1(0x1529140, 0xc00032aa50, 0xc000c6ab60, 0xc00052b078, 0xc000ac6140, 0x0)
	github.com/elves/elvish/pkg/eval/compile_effect.go:147 +0x3f
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).exec
	github.com/elves/elvish/pkg/eval/compile_effect.go:146 +0x225
Exception: elvish exited with 2
[tty 28], line 1: elvish
```

**Comment by iwoloschin** [comment]
I am getting something similar when trying to tab complete `ssh -o Pu<tab>` (for `PubkeyAuthentication=`). Since this is relying on your [ssh](https://github.com/zzamboni/elvish-completions/blob/master/ssh.elv) completion module I'm assuming the real issue is in your [completion framework](https://github.com/zzamboni/elvish-completions/blob/master/comp.elv)?

**Comment by zzamboni** [comment]
Thanks! I can confirm this is fixed now.
