### ISSUE TITLE
Panic on tab completion of non-existing namespace variables

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#1209]
Attempting to do tab-completion of *variables* (not commands) within a namespace when no completions are available results in a panic.

```
[~]|> elvish -buildinfo
Version: v0.14.0-209-g0e0a0485
Go version: go1.15.6
Reproducible build: true
```

# First example

Completing variable in an argument

```
[~]|> put $edit:foo
goroutine 1 [running]:
github.com/elves/elvish/pkg/sys.DumpStack(0xc00034c080, 0x142fbc0)
	github.com/elves/elvish/pkg/sys/dumpstack.go:10 +0x9f
github.com/elves/elvish/pkg/shell.handlePanic()
	github.com/elves/elvish/pkg/shell/interact.go:38 +0x85
panic(0x142fbc0, 0x1782dc0)
	runtime/panic.go:969 +0x1b9
github.com/elves/elvish/pkg/eval.(*Evaler).PurelyEvalPrimary(0xc000218c30, 0xc00028aa80, 0xc000f97e48, 0xc000d6b380)
	github.com/elves/elvish/pkg/eval/purely_eval.go:77 +0x145
github.com/elves/elvish/pkg/eval.(*Evaler).PurelyEvalPartialCompound(0xc000218c30, 0xc000135b20, 0xd, 0xc000f97e00, 0x12da891, 0xc000135b90, 0xc000135b90)
	github.com/elves/elvish/pkg/eval/purely_eval.go:36 +0x117
github.com/elves/elvish/pkg/edit.pureEvaler.PurelyEvalPartialCompound(0xc000218c30, 0xc000135b20, 0xd, 0xc000135b20, 0xc000f97e48, 0x13f5ba0, 0xc000f97e48)
	github.com/elves/elvish/pkg/edit/completion.go:530 +0x3f
github.com/elves/elvish/pkg/edit/complete.primaryInSimpleCompound(0xc00028aa80, 0x15373e0, 0xc000218c30, 0xc000f97e00, 0xc000f97e60, 0x0)
	github.com/elves/elvish/pkg/edit/complete/node_utils.go:36 +0xb5
github.com/elves/elvish/pkg/edit/complete.completeCommand(0x1532560, 0xc00028aa80, 0x15373e0, 0xc000218c30, 0xc0006daf30, 0xc000d833a0, 0x0, 0xc000f97e00, 0x14adcb5, 0xd, ...)
	github.com/elves/elvish/pkg/edit/complete/completers.go:87 +0x205
github.com/elves/elvish/pkg/edit/complete.Complete(0xc000ea1d80, 0xd, 0xd, 0x15373e0, 0xc000218c30, 0xc0006daf30, 0xc000d833a0, 0x0, 0x0, 0xc00034c788)
	github.com/elves/elvish/pkg/edit/complete/complete.go:90 +0x269
github.com/elves/elvish/pkg/edit.completionStart(0x1537fe0, 0xc0000e21c0, 0x152b1c0, 0xc0001262a0, 0x15373e0, 0xc000218c30, 0xc0006daf30, 0xc000d833a0, 0xc0005a1901)
	github.com/elves/elvish/pkg/edit/completion.go:162 +0xf5
github.com/elves/elvish/pkg/edit.initCompletion.func4()
	github.com/elves/elvish/pkg/edit/completion.go:240 +0xaa
reflect.Value.call(0x1406aa0, 0xc0001262d0, 0x13, 0x14a72a0, 0x4, 0x0, 0x0, 0x0, 0x1, 0x1790ed0, ...)
	reflect/value.go:476 +0x8c7
reflect.Value.Call(0x1406aa0, 0xc0001262d0, 0x13, 0x0, 0x0, 0x0, 0xc000f0dbc0, 0x136f1d8, 0x0)
	reflect/value.go:337 +0xb9
github.com/elves/elvish/pkg/eval.(*goFn).Call(0xc0000d5880, 0xc000135880, 0x0, 0x0, 0x0, 0xc000200690, 0x1, 0xc000135880)
	github.com/elves/elvish/pkg/eval/go_fn.go:232 +0x658
github.com/elves/elvish/pkg/eval.(*Evaler).Call.func1(0xc000135880, 0xc000135880, 0x20)
	github.com/elves/elvish/pkg/eval/eval.go:322 +0x62
github.com/elves/elvish/pkg/eval.(*Evaler).execOp(0xc000218c30, 0xc000d83380, 0x14af625, 0x10, 0x0, 0x0, 0x0, 0xc000d83360, 0x3, 0x3, ...)
	github.com/elves/elvish/pkg/eval/eval.go:343 +0x1aa
github.com/elves/elvish/pkg/eval.(*Evaler).Call(0xc000218c30, 0x152a5c0, 0xc0000d5880, 0x0, 0x0, 0x0, 0x0, 0x14af625, 0x10, 0xc000d83360, ...)
	github.com/elves/elvish/pkg/eval/eval.go:323 +0x290
github.com/elves/elvish/pkg/edit.callWithNotifyPorts(0x152ec20, 0xc0000d3880, 0xc000218c30, 0x152a5c0, 0xc0000d5880, 0x0, 0x0, 0x0)
	github.com/elves/elvish/pkg/edit/key_binding.go:67 +0x1d2
github.com/elves/elvish/pkg/edit.mapBinding.Handle(0x152ec20, 0xc0000d3880, 0xc000218c30, 0xc0000bac80, 0x1, 0x1, 0x152b100, 0xc00084d290, 0x100d4af)
	github.com/elves/elvish/pkg/edit/key_binding.go:41 +0x1c5
github.com/elves/elvish/pkg/cli.(*codeArea).handleKeyEvent(0xc00010e100, 0x9, 0x14cd900)
	github.com/elves/elvish/pkg/cli/codearea.go:289 +0x10e
github.com/elves/elvish/pkg/cli.(*codeArea).Handle(0xc00010e100, 0x152b100, 0xc00084d288, 0x0)
	github.com/elves/elvish/pkg/cli/codearea.go:164 +0xb6
github.com/elves/elvish/pkg/cli.(*app).handle(0xc0000e21c0, 0x145caa0, 0xc00084d288)
	github.com/elves/elvish/pkg/cli/app.go:171 +0x27f
github.com/elves/elvish/pkg/cli.(*loop).Run(0xc0000d3b40, 0xc000096101, 0xc0000964e0, 0xc0000e21c0, 0xc00030e280)
	github.com/elves/elvish/pkg/cli/loop.go:129 +0x242
github.com/elves/elvish/pkg/cli.(*app).ReadCode(0xc0000e21c0, 0x0, 0x0, 0x0, 0x0)
	github.com/elves/elvish/pkg/cli/app.go:334 +0x3ed
github.com/elves/elvish/pkg/edit.(*Editor).ReadCode(0xc0000d3880, 0xc0000aa010, 0xc0000aa008, 0xc0000aa010, 0xc000de1508)
	github.com/elves/elvish/pkg/edit/editor.go:98 +0x33
github.com/elves/elvish/pkg/shell.Interact(0xc0000aa000, 0xc0000aa008, 0xc0000aa010, 0xc00020fca0)
	github.com/elves/elvish/pkg/shell/interact.go:80 +0x5be
github.com/elves/elvish/pkg/shell.program.Run(0xc0000aa000, 0xc0000aa008, 0xc0000aa010, 0xc000276000, 0xc0000a0190, 0x0, 0x0, 0x17c2fa0, 0xc00020ff68)
	github.com/elves/elvish/pkg/shell/shell.go:40 +0x2c9
github.com/elves/elvish/pkg/prog.Run(0xc0000aa000, 0xc0000aa008, 0xc0000aa010, 0xc0000a0190, 0x1, 0x1, 0xc00020ff48, 0x3, 0x3, 0x0)
	github.com/elves/elvish/pkg/prog/prog.go:134 +0x2b8
main.main()
	github.com/elves/elvish/main.go:17 +0x11f

goroutine 34 [chan receive]:
github.com/elves/elvish/pkg/eval.getBlackholeChan.func1(0xc000248060)
	github.com/elves/elvish/pkg/eval/port.go:67 +0x47
created by github.com/elves/elvish/pkg/eval.getBlackholeChan
	github.com/elves/elvish/pkg/eval/port.go:66 +0x58

goroutine 36 [syscall]:
os/signal.signal_recv(0x152ff60)
	runtime/sigqueue.go:144 +0x9d
os/signal.loop()
	os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	os/signal/signal.go:150 +0x45

goroutine 20 [chan receive]:
github.com/elves/elvish/pkg/shell.setupShell.func1(0xc000206840, 0xc0000aa000, 0xc0000aa008, 0xc0000aa010)
	github.com/elves/elvish/pkg/shell/shell.go:51 +0xa5
created by github.com/elves/elvish/pkg/shell.setupShell
	github.com/elves/elvish/pkg/shell/shell.go:50 +0xf9

goroutine 21 [chan receive]:
github.com/elves/elvish/pkg/cli/prompt.(*Prompt).loop(0xc0000d43f0)
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:77 +0xc8
created by github.com/elves/elvish/pkg/cli/prompt.New
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:70 +0x165

goroutine 22 [chan receive]:
github.com/elves/elvish/pkg/cli/prompt.(*Prompt).loop(0xc0000d44d0)
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:77 +0xc8
created by github.com/elves/elvish/pkg/cli/prompt.New
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:70 +0x165

goroutine 11972 [semacquire]:
sync.runtime_Semacquire(0xc0006b0ad8)
	runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0006b0ad0)
	sync/waitgroup.go:130 +0x65
github.com/elves/elvish/pkg/eval.(*pipelineOp).exec.func2(0xc0006b0ad0, 0xc00098c540, 0xc000775180, 0xc0004020c8, 0x1, 0x1)
	github.com/elves/elvish/pkg/eval/compile_effect.go:170 +0x45
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).exec
	github.com/elves/elvish/pkg/eval/compile_effect.go:169 +0x29c

goroutine 11971 [syscall]:
syscall.syscall6(0x1084620, 0x11bec, 0xc000be9acc, 0x0, 0xc000e0a000, 0x0, 0x0, 0x0, 0x0, 0x0)
	runtime/sys_darwin.go:85 +0x2e
syscall.wait4(0x11bec, 0xc000be9acc, 0x0, 0xc000e0a000, 0x90, 0x149bbc0, 0x1)
	syscall/zsyscall_darwin_amd64.go:44 +0x87
syscall.Wait4(0x11bec, 0xc000be9b1c, 0x0, 0xc000e0a000, 0x47, 0xc000cf31a0, 0x6)
	syscall/syscall_bsd.go:129 +0x51
os.(*Process).wait(0xc0003b83f0, 0x47, 0xc000cf31a0, 0x6)
	os/exec_unix.go:43 +0x85
os.(*Process).Wait(...)
	os/exec.go:125
github.com/elves/elvish/pkg/eval.ExternalCmd.Call(0xc0001120f0, 0x47, 0xc00098c5b0, 0xc000114180, 0x5, 0x8, 0xc0005a09c0, 0xc000466000, 0xc000624140)
	github.com/elves/elvish/pkg/eval/external_cmd.go:89 +0x35a
github.com/elves/elvish/pkg/eval.(*formOp).exec(0xc0007b0a50, 0xc00098c5b0, 0x0, 0x0)
	github.com/elves/elvish/pkg/eval/compile_effect.go:382 +0x646
github.com/elves/elvish/pkg/eval.(*pipelineOp).exec.func1(0x152a5a0, 0xc0007b0a50, 0xc00098c5b0, 0xc0004020c8, 0xc0006b0ad0, 0x0)
	github.com/elves/elvish/pkg/eval/compile_effect.go:150 +0x3f
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).exec
	github.com/elves/elvish/pkg/eval/compile_effect.go:149 +0x225

runtime error: invalid memory address or nil pointer dereference

Execing recovery shell /bin/sh
```

# Second example

Completing variable in the command head position.

```
[~]|> $re:foob
goroutine 1 [running]:
github.com/elves/elvish/pkg/sys.DumpStack(0xc000178080, 0x142fbc0)
	github.com/elves/elvish/pkg/sys/dumpstack.go:10 +0x9f
github.com/elves/elvish/pkg/shell.handlePanic()
	github.com/elves/elvish/pkg/shell/interact.go:38 +0x85
panic(0x142fbc0, 0x1782dc0)
	runtime/panic.go:969 +0x1b9
github.com/elves/elvish/pkg/eval.(*Evaler).PurelyEvalPrimary(0xc00014f6c0, 0xc0000d6540, 0xc00102be48, 0xc000b851d0)
	github.com/elves/elvish/pkg/eval/purely_eval.go:77 +0x145
github.com/elves/elvish/pkg/eval.(*Evaler).PurelyEvalPartialCompound(0xc00014f6c0, 0xc000abe540, 0x8, 0xc00102be00, 0x12da891, 0xc000abe5b0, 0xc000abe5b0)
	github.com/elves/elvish/pkg/eval/purely_eval.go:36 +0x117
github.com/elves/elvish/pkg/edit.pureEvaler.PurelyEvalPartialCompound(0xc00014f6c0, 0xc000abe540, 0x8, 0xc000abe540, 0xc00102be48, 0x13f5ba0, 0xc00102be48)
	github.com/elves/elvish/pkg/edit/completion.go:530 +0x3f
github.com/elves/elvish/pkg/edit/complete.primaryInSimpleCompound(0xc0000d6540, 0x15373e0, 0xc00014f6c0, 0xc00102be00, 0xc00102be60, 0x0)
	github.com/elves/elvish/pkg/edit/complete/node_utils.go:36 +0xb5
github.com/elves/elvish/pkg/edit/complete.completeCommand(0x1532560, 0xc0000d6540, 0x15373e0, 0xc00014f6c0, 0xc0004eccf0, 0xc000c4eba0, 0x0, 0xc00102be00, 0x14adcb5, 0xd, ...)
	github.com/elves/elvish/pkg/edit/complete/completers.go:87 +0x205
github.com/elves/elvish/pkg/edit/complete.Complete(0xc0008d60a0, 0x8, 0x8, 0x15373e0, 0xc00014f6c0, 0xc0004eccf0, 0xc000c4eba0, 0x0, 0x0, 0xc000178788)
	github.com/elves/elvish/pkg/edit/complete/complete.go:90 +0x269
github.com/elves/elvish/pkg/edit.completionStart(0x1537fe0, 0xc0001ae000, 0x152b1c0, 0xc0001828a0, 0x15373e0, 0xc00014f6c0, 0xc0004eccf0, 0xc000c4eba0, 0xc00042db01)
	github.com/elves/elvish/pkg/edit/completion.go:162 +0xf5
github.com/elves/elvish/pkg/edit.initCompletion.func4()
	github.com/elves/elvish/pkg/edit/completion.go:240 +0xaa
reflect.Value.call(0x1406aa0, 0xc0001828d0, 0x13, 0x14a72a0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x1790ed0, ...)
	reflect/value.go:476 +0x8c7
reflect.Value.Call(0x1406aa0, 0xc0001828d0, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	reflect/value.go:337 +0xb9
github.com/elves/elvish/pkg/eval.(*goFn).Call(0xc0001a35e0, 0xc000abe380, 0x0, 0x0, 0x0, 0xc000208090, 0x1, 0xc000abe380)
	github.com/elves/elvish/pkg/eval/go_fn.go:232 +0x658
github.com/elves/elvish/pkg/eval.(*Evaler).Call.func1(0xc000abe380, 0xc000abe380, 0x20)
	github.com/elves/elvish/pkg/eval/eval.go:322 +0x62
github.com/elves/elvish/pkg/eval.(*Evaler).execOp(0xc00014f6c0, 0xc000c4eb80, 0x14af625, 0x10, 0x0, 0x0, 0x0, 0xc000c4eb60, 0x3, 0x3, ...)
	github.com/elves/elvish/pkg/eval/eval.go:343 +0x1aa
github.com/elves/elvish/pkg/eval.(*Evaler).Call(0xc00014f6c0, 0x152a5c0, 0xc0001a35e0, 0x0, 0x0, 0x0, 0x0, 0x14af625, 0x10, 0xc000c4eb60, ...)
	github.com/elves/elvish/pkg/eval/eval.go:323 +0x290
github.com/elves/elvish/pkg/edit.callWithNotifyPorts(0x152ec20, 0xc00018e040, 0xc00014f6c0, 0x152a5c0, 0xc0001a35e0, 0x0, 0x0, 0x0)
	github.com/elves/elvish/pkg/edit/key_binding.go:67 +0x1d2
github.com/elves/elvish/pkg/edit.mapBinding.Handle(0x152ec20, 0xc00018e040, 0xc00014f6c0, 0xc000188240, 0x1, 0x1, 0x152b100, 0xc0008d6768, 0x100d4af)
	github.com/elves/elvish/pkg/edit/key_binding.go:41 +0x1c5
github.com/elves/elvish/pkg/cli.(*codeArea).handleKeyEvent(0xc0001b0000, 0x9, 0x14cd900)
	github.com/elves/elvish/pkg/cli/codearea.go:289 +0x10e
github.com/elves/elvish/pkg/cli.(*codeArea).Handle(0xc0001b0000, 0x152b100, 0xc0008d6760, 0x0)
	github.com/elves/elvish/pkg/cli/codearea.go:164 +0xb6
github.com/elves/elvish/pkg/cli.(*app).handle(0xc0001ae000, 0x145caa0, 0xc0008d6760)
	github.com/elves/elvish/pkg/cli/app.go:171 +0x27f
github.com/elves/elvish/pkg/cli.(*loop).Run(0xc00018e300, 0xc0001a4001, 0xc0001a42a0, 0xc0001ae000, 0xc0007debe4)
	github.com/elves/elvish/pkg/cli/loop.go:129 +0x242
github.com/elves/elvish/pkg/cli.(*app).ReadCode(0xc0001ae000, 0x0, 0x0, 0x0, 0x0)
	github.com/elves/elvish/pkg/cli/app.go:334 +0x3ed
github.com/elves/elvish/pkg/edit.(*Editor).ReadCode(0xc00018e040, 0xc000010020, 0xc000010020, 0xc00014f6c0, 0xc000029aa0)
	github.com/elves/elvish/pkg/edit/editor.go:98 +0x33
github.com/elves/elvish/pkg/shell.Interact(0xc000010010, 0xc000010018, 0xc000010020, 0xc000179ca0)
	github.com/elves/elvish/pkg/shell/interact.go:80 +0x5be
github.com/elves/elvish/pkg/shell.program.Run(0xc000010010, 0xc000010018, 0xc000010020, 0xc00017a100, 0xc0000201b0, 0x0, 0x0, 0x17c2fa0, 0xc000179f68)
	github.com/elves/elvish/pkg/shell/shell.go:40 +0x2c9
github.com/elves/elvish/pkg/prog.Run(0xc000010010, 0xc000010018, 0xc000010020, 0xc0000201b0, 0x1, 0x1, 0xc000179f48, 0x3, 0x3, 0x0)
	github.com/elves/elvish/pkg/prog/prog.go:134 +0x2b8
main.main()
	github.com/elves/elvish/main.go:17 +0x11f

goroutine 7 [chan receive]:
github.com/elves/elvish/pkg/eval.getBlackholeChan.func1(0xc000108180)
	github.com/elves/elvish/pkg/eval/port.go:67 +0x47
created by github.com/elves/elvish/pkg/eval.getBlackholeChan
	github.com/elves/elvish/pkg/eval/port.go:66 +0x58

goroutine 9 [syscall]:
os/signal.signal_recv(0x152ff60)
	runtime/sigqueue.go:144 +0x9d
os/signal.loop()
	os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	os/signal/signal.go:150 +0x45

goroutine 18 [chan receive]:
github.com/elves/elvish/pkg/shell.setupShell.func1(0xc000030ba0, 0xc000010010, 0xc000010018, 0xc000010020)
	github.com/elves/elvish/pkg/shell/shell.go:51 +0xa5
created by github.com/elves/elvish/pkg/shell.setupShell
	github.com/elves/elvish/pkg/shell/shell.go:50 +0xf9

goroutine 19 [chan receive]:
github.com/elves/elvish/pkg/cli/prompt.(*Prompt).loop(0xc0001a22a0)
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:77 +0xc8
created by github.com/elves/elvish/pkg/cli/prompt.New
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:70 +0x165

goroutine 20 [chan receive]:
github.com/elves/elvish/pkg/cli/prompt.(*Prompt).loop(0xc0001a2380)
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:77 +0xc8
created by github.com/elves/elvish/pkg/cli/prompt.New
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:70 +0x165

goroutine 11613 [semacquire]:
sync.runtime_Semacquire(0xc000a01f64)
	runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc000a01f64)
	sync/waitgroup.go:130 +0x65
github.com/elves/elvish/pkg/eval.(*pipelineOp).exec.func2(0xc000a01f64, 0xc0003eca80, 0xc000599d80, 0xc000a064e0, 0x1, 0x1)
	github.com/elves/elvish/pkg/eval/compile_effect.go:170 +0x45
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).exec
	github.com/elves/elvish/pkg/eval/compile_effect.go:169 +0x29c

goroutine 11612 [syscall]:
syscall.syscall6(0x1084620, 0x11e62, 0xc000a2dacc, 0x0, 0xc000aae120, 0x0, 0x0, 0x0, 0x0, 0x0)
	runtime/sys_darwin.go:85 +0x2e
syscall.wait4(0x11e62, 0xc000a2dacc, 0x0, 0xc000aae120, 0x90, 0x149bbc0, 0x1)
	syscall/zsyscall_darwin_amd64.go:44 +0x87
syscall.Wait4(0x11e62, 0xc000a2db1c, 0x0, 0xc000aae120, 0x47, 0xc00094a9c0, 0x6)
	syscall/syscall_bsd.go:129 +0x51
os.(*Process).wait(0xc0003d2900, 0x47, 0xc00094a9c0, 0x6)
	os/exec_unix.go:43 +0x85
os.(*Process).Wait(...)
	os/exec.go:125
github.com/elves/elvish/pkg/eval.ExternalCmd.Call(0xc000026280, 0x47, 0xc0003ecb60, 0xc000d88200, 0x5, 0x8, 0xc000a976b0, 0xc0003d6000, 0xc000136190)
	github.com/elves/elvish/pkg/eval/external_cmd.go:89 +0x35a
github.com/elves/elvish/pkg/eval.(*formOp).exec(0xc0005eca50, 0xc0003ecb60, 0x0, 0x0)
	github.com/elves/elvish/pkg/eval/compile_effect.go:382 +0x646
github.com/elves/elvish/pkg/eval.(*pipelineOp).exec.func1(0x152a5a0, 0xc0005eca50, 0xc0003ecb60, 0xc000a064e0, 0xc000a01f64, 0x0)
	github.com/elves/elvish/pkg/eval/compile_effect.go:150 +0x3f
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).exec
	github.com/elves/elvish/pkg/eval/compile_effect.go:149 +0x225

runtime error: invalid memory address or nil pointer dereference

Execing recovery shell /bin/sh
```

**Comment by zzamboni** [comment]
Update: the panic also seems to happen on some existing variables, for example, trying to complete `$edit:after-readline` (this is how I discovered the issue):

```
[~]|> put $edit:after-readline
▶ [<closure 0xc000c69900> <closure 0xc0002b43c0> <closure 0xc0007acf00> <closure 0xc0008ab860>]
[~]|> put $edit:after
goroutine 1 [running]:
github.com/elves/elvish/pkg/sys.DumpStack(0xc0005c6080, 0x142fbc0)
	github.com/elves/elvish/pkg/sys/dumpstack.go:10 +0x9f
github.com/elves/elvish/pkg/shell.handlePanic()
	github.com/elves/elvish/pkg/shell/interact.go:38 +0x85
panic(0x142fbc0, 0x1782dc0)
	runtime/panic.go:969 +0x1b9
github.com/elves/elvish/pkg/eval.(*Evaler).PurelyEvalPrimary(0xc0001d71e0, 0xc0001163c0, 0xc00100e348, 0xc000704e10)
	github.com/elves/elvish/pkg/eval/purely_eval.go:77 +0x145
github.com/elves/elvish/pkg/eval.(*Evaler).PurelyEvalPartialCompound(0xc0001d71e0, 0xc0003392d0, 0xf, 0xc00100e300, 0x12da891, 0xc000339340, 0xc000339340)
	github.com/elves/elvish/pkg/eval/purely_eval.go:36 +0x117
github.com/elves/elvish/pkg/edit.pureEvaler.PurelyEvalPartialCompound(0xc0001d71e0, 0xc0003392d0, 0xf, 0xc0003392d0, 0xc00100e348, 0x13f5ba0, 0xc00100e348)
	github.com/elves/elvish/pkg/edit/completion.go:530 +0x3f
github.com/elves/elvish/pkg/edit/complete.primaryInSimpleCompound(0xc0001163c0, 0x15373e0, 0xc0001d71e0, 0xc00100e300, 0xc00100e360, 0x0)
	github.com/elves/elvish/pkg/edit/complete/node_utils.go:36 +0xb5
github.com/elves/elvish/pkg/edit/complete.completeCommand(0x1532560, 0xc0001163c0, 0x15373e0, 0xc0001d71e0, 0xc0004606c0, 0xc000a3be40, 0x0, 0xc00100e300, 0x14adcb5, 0xd, ...)
	github.com/elves/elvish/pkg/edit/complete/completers.go:87 +0x205
github.com/elves/elvish/pkg/edit/complete.Complete(0xc000db0030, 0xf, 0xf, 0x15373e0, 0xc0001d71e0, 0xc0004606c0, 0xc000a3be40, 0x0, 0x0, 0xc0005c6788)
	github.com/elves/elvish/pkg/edit/complete/complete.go:90 +0x269
github.com/elves/elvish/pkg/edit.completionStart(0x1537fe0, 0xc000136000, 0x152b1c0, 0xc000112870, 0x15373e0, 0xc0001d71e0, 0xc0004606c0, 0xc000a3be40, 0xc000459901)
	github.com/elves/elvish/pkg/edit/completion.go:162 +0xf5
github.com/elves/elvish/pkg/edit.initCompletion.func4()
	github.com/elves/elvish/pkg/edit/completion.go:240 +0xaa
reflect.Value.call(0x1406aa0, 0xc0001128a0, 0x13, 0x14a72a0, 0x4, 0x0, 0x0, 0x0, 0x1, 0x1790ed0, ...)
	reflect/value.go:476 +0x8c7
reflect.Value.Call(0x1406aa0, 0xc0001128a0, 0x13, 0x0, 0x0, 0x0, 0xc000d221a0, 0x8, 0x0)
	reflect/value.go:337 +0xb9
github.com/elves/elvish/pkg/eval.(*goFn).Call(0xc0001315e0, 0xc000338f50, 0x0, 0x0, 0x0, 0xc00020a180, 0x1, 0xc000338f50)
	github.com/elves/elvish/pkg/eval/go_fn.go:232 +0x658
github.com/elves/elvish/pkg/eval.(*Evaler).Call.func1(0xc000338f50, 0xc000338f50, 0x20)
	github.com/elves/elvish/pkg/eval/eval.go:322 +0x62
github.com/elves/elvish/pkg/eval.(*Evaler).execOp(0xc0001d71e0, 0xc000a3be20, 0x14af625, 0x10, 0x0, 0x0, 0x0, 0xc000a3be00, 0x3, 0x3, ...)
	github.com/elves/elvish/pkg/eval/eval.go:343 +0x1aa
github.com/elves/elvish/pkg/eval.(*Evaler).Call(0xc0001d71e0, 0x152a5c0, 0xc0001315e0, 0x0, 0x0, 0x0, 0x0, 0x14af625, 0x10, 0xc000a3be00, ...)
	github.com/elves/elvish/pkg/eval/eval.go:323 +0x290
github.com/elves/elvish/pkg/edit.callWithNotifyPorts(0x152ec20, 0xc00007c0c0, 0xc0001d71e0, 0x152a5c0, 0xc0001315e0, 0x0, 0x0, 0x0)
	github.com/elves/elvish/pkg/edit/key_binding.go:67 +0x1d2
github.com/elves/elvish/pkg/edit.mapBinding.Handle(0x152ec20, 0xc00007c0c0, 0xc0001d71e0, 0xc00000e2c0, 0x1, 0x1, 0x152b100, 0xc0007d76f8, 0x100d4af)
	github.com/elves/elvish/pkg/edit/key_binding.go:41 +0x1c5
github.com/elves/elvish/pkg/cli.(*codeArea).handleKeyEvent(0xc000138000, 0x9, 0x14cd900)
	github.com/elves/elvish/pkg/cli/codearea.go:289 +0x10e
github.com/elves/elvish/pkg/cli.(*codeArea).Handle(0xc000138000, 0x152b100, 0xc0007d76f0, 0x0)
	github.com/elves/elvish/pkg/cli/codearea.go:164 +0xb6
github.com/elves/elvish/pkg/cli.(*app).handle(0xc000136000, 0x145caa0, 0xc0007d76f0)
	github.com/elves/elvish/pkg/cli/app.go:171 +0x27f
github.com/elves/elvish/pkg/cli.(*loop).Run(0xc00007c380, 0xc000108001, 0xc000eb2000, 0xc000136000, 0xc000c10884)
	github.com/elves/elvish/pkg/cli/loop.go:129 +0x242
github.com/elves/elvish/pkg/cli.(*app).ReadCode(0xc000136000, 0x0, 0x0, 0x0, 0x0)
	github.com/elves/elvish/pkg/cli/app.go:334 +0x3ed
github.com/elves/elvish/pkg/edit.(*Editor).ReadCode(0xc00007c0c0, 0xc00018a010, 0xc00018a008, 0xc00018a010, 0xc000db0110)
	github.com/elves/elvish/pkg/edit/editor.go:98 +0x33
github.com/elves/elvish/pkg/shell.Interact(0xc00018a000, 0xc00018a008, 0xc00018a010, 0xc00011bca0)
	github.com/elves/elvish/pkg/shell/interact.go:80 +0x5be
github.com/elves/elvish/pkg/shell.program.Run(0xc00018a000, 0xc00018a008, 0xc00018a010, 0xc0001fc080, 0xc000180190, 0x0, 0x0, 0x17c2fa0, 0xc00011bf68)
	github.com/elves/elvish/pkg/shell/shell.go:40 +0x2c9
github.com/elves/elvish/pkg/prog.Run(0xc00018a000, 0xc00018a008, 0xc00018a010, 0xc000180190, 0x1, 0x1, 0xc00011bf48, 0x3, 0x3, 0x0)
	github.com/elves/elvish/pkg/prog/prog.go:134 +0x2b8
main.main()
	github.com/elves/elvish/main.go:17 +0x11f

goroutine 20 [chan receive]:
github.com/elves/elvish/pkg/eval.getBlackholeChan.func1(0xc0001a2120)
	github.com/elves/elvish/pkg/eval/port.go:67 +0x47
created by github.com/elves/elvish/pkg/eval.getBlackholeChan
	github.com/elves/elvish/pkg/eval/port.go:66 +0x58

goroutine 22 [syscall]:
os/signal.signal_recv(0x152ff60)
	runtime/sigqueue.go:144 +0x9d
os/signal.loop()
	os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	os/signal/signal.go:150 +0x45

goroutine 5 [chan receive]:
github.com/elves/elvish/pkg/shell.setupShell.func1(0xc00018cc00, 0xc00018a000, 0xc00018a008, 0xc00018a010)
	github.com/elves/elvish/pkg/shell/shell.go:51 +0xa5
created by github.com/elves/elvish/pkg/shell.setupShell
	github.com/elves/elvish/pkg/shell/shell.go:50 +0xf9

goroutine 6 [chan receive]:
github.com/elves/elvish/pkg/cli/prompt.(*Prompt).loop(0xc0001302a0)
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:77 +0xc8
created by github.com/elves/elvish/pkg/cli/prompt.New
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:70 +0x165

goroutine 7 [chan receive]:
github.com/elves/elvish/pkg/cli/prompt.(*Prompt).loop(0xc000130380)
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:77 +0xc8
created by github.com/elves/elvish/pkg/cli/prompt.New
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:70 +0x165

goroutine 11995 [syscall]:
syscall.syscall6(0x1084620, 0x122cc, 0xc000a79acc, 0x0, 0xc000da2120, 0x0, 0x0, 0x0, 0x0, 0x0)
	runtime/sys_darwin.go:85 +0x2e
syscall.wait4(0x122cc, 0xc000a79acc, 0x0, 0xc000da2120, 0x90, 0x149bbc0, 0x1)
	syscall/zsyscall_darwin_amd64.go:44 +0x87
syscall.Wait4(0x122cc, 0xc000a79b1c, 0x0, 0xc000da2120, 0x47, 0xc000b7e960, 0x6)
	syscall/syscall_bsd.go:129 +0x51
os.(*Process).wait(0xc0009fc750, 0x47, 0xc000b7e960, 0x6)
	os/exec_unix.go:43 +0x85
os.(*Process).Wait(...)
	os/exec.go:125
github.com/elves/elvish/pkg/eval.ExternalCmd.Call(0xc000026230, 0x47, 0xc0007c47e0, 0xc00069c000, 0x5, 0x8, 0xc000b7ad50, 0xc000662000, 0xc0000262d0)
	github.com/elves/elvish/pkg/eval/external_cmd.go:89 +0x35a
github.com/elves/elvish/pkg/eval.(*formOp).exec(0xc00082c9a0, 0xc0007c47e0, 0x0, 0x0)
	github.com/elves/elvish/pkg/eval/compile_effect.go:382 +0x646
github.com/elves/elvish/pkg/eval.(*pipelineOp).exec.func1(0x152a5a0, 0xc00082c9a0, 0xc0007c47e0, 0xc0003e40e8, 0xc00064c210, 0xc000032000)
	github.com/elves/elvish/pkg/eval/compile_effect.go:150 +0x3f
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).exec
	github.com/elves/elvish/pkg/eval/compile_effect.go:149 +0x225

goroutine 11996 [semacquire]:
sync.runtime_Semacquire(0xc00064c218)
	runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc00064c210)
	sync/waitgroup.go:130 +0x65
github.com/elves/elvish/pkg/eval.(*pipelineOp).exec.func2(0xc00064c210, 0xc0007c4770, 0xc00081ce80, 0xc0003e40e8, 0x1, 0x1)
	github.com/elves/elvish/pkg/eval/compile_effect.go:170 +0x45
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).exec
	github.com/elves/elvish/pkg/eval/compile_effect.go:169 +0x29c

runtime error: invalid memory address or nil pointer dereference

Execing recovery shell /bin/sh
```
