### ISSUE TITLE
Panic when trying to add new name to any namespace

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1214]
This failure occurs against the latest master commit (56ceeedd21f538515951d8802cd87bdc01cf4e5f) as I write this:

```
> builtin:wtf = $true
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x135e10e]

goroutine 16628 [running]:
github.com/elves/elvish/pkg/eval.(*assignOp).exec(0xc000438a00, 0xc0005ba7e0, 0xc0001a2e28
, 0x0)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_lvalue.go:122 +0x2ce
github.com/elves/elvish/pkg/eval.(*formOp).exec(0xc0006f73f0, 0xc0005ba7e0, 0x0, 0x0)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:359 +0x965
github.com/elves/elvish/pkg/eval.(*pipelineOp).exec.func1(0x1529bc0, 0xc0006f73f0, 0xc0005
ba7e0, 0xc00067a5f0, 0xc0002132a0, 0xc000438b00)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:116 +0x3f
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).exec
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:115 +0x228
```

**Comment by krader1961** [comment]
My original problem description was perhaps overly specific since this applies to any of the ostensibly read-only "builtin" namespaces which also includes `edit`, `math`, `str`, etc.

**Comment by xiaq** [comment]
This is in fact happening for any namespace:

```
~> n: = (ns [&])
~> n:a = b
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x75df0e]

goroutine 282 [running]:
github.com/elves/elvish/pkg/eval.(*assignOp).exec(0xc00015a400, 0xc000158770, 0xc00019ce28, 0x0)
        github.com/elves/elvish/pkg/eval/compile_lvalue.go:122 +0x2ce
github.com/elves/elvish/pkg/eval.(*formOp).exec(0xc0001d6e70, 0xc000158770, 0x0, 0x0)
        github.com/elves/elvish/pkg/eval/compile_effect.go:359 +0x965
github.com/elves/elvish/pkg/eval.(*pipelineOp).exec.func1(0x927e00, 0xc0001d6e70, 0xc000158770, 0xc000304830, 0xc000156630, 0xc000156300)
        github.com/elves/elvish/pkg/eval/compile_effect.go:116 +0x3f
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).exec
        github.com/elves/elvish/pkg/eval/compile_effect.go:115 +0x228
```
