### ISSUE TITLE
Panic when using alias module

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#1215]
Not sure if this is related or the same as #1214 - seems similar to me.

```
> elvish -buildinfo
Version: v0.14.0-233-g56ceeedd
Go version: go1.15.6
Reproducible build: true
```

The panic seems to happen when reading existing aliases from their files, but only within `rc.elv`. The same commands executed from an interactive session work fine.

A minimal `rc.elv` to trigger the bug:
```
use github.com/zzamboni/elvish-modules/alias
alias:new foo echo bar
```

And a sample session showing the behavior:
```
[~/.elvish]─[⎇ master]─[+●]|> rm -rf aliases/
[~/.elvish]─[⎇ master]─[●]|> elvish
### This first session works fine, it causes the ~/.elvish/alises/foo.elv` file to be written
~/.elvish> elvish
### The second session tries to read that file, and panics.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x131a6b4]

goroutine 141 [running]:
github.com/elves/elvish/pkg/eval/vars.MakeElement(0x0, 0x0, 0xc000020fe0, 0x1, 0x1, 0x0, 0x0, 0x10, 0x1439100)
	github.com/elves/elvish/pkg/eval/vars/element.go:58 +0x54
github.com/elves/elvish/pkg/eval.derefLValue(0xc000217ab0, 0x69, 0x7b, 0xc0002013e0, 0xc000020eb0, 0x1, 0x1, 0xc00002a4a0, 0x2, 0x2, ...)
	github.com/elves/elvish/pkg/eval/compile_lvalue.go:172 +0x1b3
github.com/elves/elvish/pkg/eval.(*assignOp).exec(0xc00007c880, 0xc000217ab0, 0xc000063e28, 0x0)
	github.com/elves/elvish/pkg/eval/compile_lvalue.go:103 +0x191
github.com/elves/elvish/pkg/eval.(*formOp).exec(0xc000236210, 0xc000217ab0, 0x0, 0x0)
	github.com/elves/elvish/pkg/eval/compile_effect.go:359 +0x965
github.com/elves/elvish/pkg/eval.(*pipelineOp).exec.func1(0x1529c00, 0xc000236210, 0xc000217ab0, 0xc000020fc0, 0xc00002a4e0, 0x0)
	github.com/elves/elvish/pkg/eval/compile_effect.go:116 +0x3f
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).exec
	github.com/elves/elvish/pkg/eval/compile_effect.go:115 +0x228
Exception: elvish exited with 2
```

Note that running the same commands from an interactive session does not cause a panic:
```
~/.elvish> use github.com/zzamboni/elvish-modules/alias
~/.elvish> alias:new foo echo bar
~/.elvish>
```

**Comment by xiaq** [comment]
With the last commit this is now an exception instead:

```
Exception: no variable $alias:aliases[foo]
Traceback:
  [eval 1], line 4:
    alias:aliases[foo] = $foo~
  /home/xiaq/.elvish/lib/github.com/zzamboni/elvish-modules/alias.elv, line 21:
      eval $str
  /home/xiaq/.elvish/lib/github.com/zzamboni/elvish-modules/alias.elv, line 90:
          -load-alias $name $file
  /home/xiaq/.elvish/lib/github.com/zzamboni/elvish-modules/alias.elv, line 95:
    init
  /home/xiaq/.elvish/rc.elv, line 91:
    use github.com/zzamboni/elvish-modules/alias
```

**Comment by xiaq** [comment]
Which is caused by a subtle change in how circular dependencies are handled.

Previously, when there is a circular dependency `a -> b -> a`, the module `b` will observe a partial `a`, containing whatever bindings were defined when `a` imports `b`. After the recent change in namespace implementation, the module `b` will always observe an empty `a`.

**Comment by xiaq** [comment]
https://github.com/zzamboni/elvish-modules/pull/14
