### ISSUE TITLE
Panic with SHELL=elvish and GDB

### ISSUE THREAD

**Issue by pontaoski** [elves/elvish#1217]
```
goroutine 38 [running]:
github.com/elves/elvish/pkg/eval.preExit(0xc0000c6380)
        /home/jpontaoski/Code/GitHub/pontaoski/elvish/pkg/eval/builtin_fn_cmd.go:122 +0x39
github.com/elves/elvish/pkg/eval.execFn(0xc0000c6380, 0xc00009a220, 0x1, 0x1, 0x0, 0x0)
        /home/jpontaoski/Code/GitHub/pontaoski/elvish/pkg/eval/builtin_fn_cmd_unix.go:37 +0x169
reflect.Value.call(0x8ceb80, 0x99dfa8, 0x13, 0x973ce2, 0x4, 0xc0000985d0, 0x2, 0x2, 0x2, 0x18, ...)
        /usr/lib/golang/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x8ceb80, 0x99dfa8, 0x13, 0xc0000985d0, 0x2, 0x2, 0x1, 0x2, 0x40e336)
        /usr/lib/golang/src/reflect/value.go:321 +0xb4
github.com/elves/elvish/pkg/eval.(*GoFn).Call(0xc0001961c0, 0xc0000c6380, 0xc00009a1e0, 0x1, 0x1, 0xc0000985a0, 0x0, 0x1)
        /home/jpontaoski/Code/GitHub/pontaoski/elvish/pkg/eval/go_fn.go:235 +0x638
github.com/elves/elvish/pkg/eval.(*formOp).invoke(0xc0000c80d0, 0xc0000c6380, 0x0, 0x0)
        /home/jpontaoski/Code/GitHub/pontaoski/elvish/pkg/eval/compile_effect.go:388 +0x8be
github.com/elves/elvish/pkg/eval.effectOp.exec(0xa2f3a0, 0xc0000c80d0, 0x0, 0x33, 0xc0000c6380, 0x0, 0x0)
        /home/jpontaoski/Code/GitHub/pontaoski/elvish/pkg/eval/op.go:33 +0x69
github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke.func1(0xa2f3a0, 0xc0000c80d0, 0x0, 0x33, 0xc0000c6380, 0xc00009c060, 0xc0000aa0a0, 0x0)
        /home/jpontaoski/Code/GitHub/pontaoski/elvish/pkg/eval/compile_effect.go:144 +0x60
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke
        /home/jpontaoski/Code/GitHub/pontaoski/elvish/pkg/eval/compile_effect.go:143 +0x23e
```

How one runs into the crash: https://asciinema.org/a/GoDZoHir8wTvLDBHYQpO9QWz7

**Comment by pontaoski** [comment]
NVM, outdated version
