### ISSUE TITLE
`use edit` creates a crash situation for elvish

### ISSUE THREAD

**Issue by crinklywrappr** [elves/elvish#1381]
## The problem
In 0.15.0, `use`ing a module which is already 'imported', and then pressing `tab` for autocomplete crashes elvish.

EDIT: I ran this on HEAD 8/15/21 and was able to reproduce the crash.

```
┌╴~ 
└╴❱❱❱ use edit
Exception: no such module: edit
[tty 9], line 1: use edit
                                                                                                                                                                              
┌╴~ 
└╴❱❱❱ edit:
goroutine 1 [running]:
github.com/elves/elvish/pkg/sys.DumpStack(0xc000186270, 0x8b4780)
	github.com/elves/elvish/pkg/sys/dumpstack.go:10 +0x9f
github.com/elves/elvish/pkg/shell.handlePanic()
	github.com/elves/elvish/pkg/shell/interact.go:39 +0x8a
panic(0x8b4780, 0xc51f60)
	runtime/panic.go:965 +0x1b9
github.com/elves/elvish/pkg/eval.(*Ns).IterateNames(0x0, 0xc00026ba10)
	github.com/elves/elvish/pkg/eval/ns.go:125 +0x26
github.com/elves/elvish/pkg/edit.eachVariableInTop(0xc00009c230, 0xc0005082d0, 0xc000431304, 0x5, 0xc00026ba10)
	github.com/elves/elvish/pkg/edit/ns_helper.go:43 +0x245
github.com/elves/elvish/pkg/edit.pureEvaler.EachVariableInNs(0xc00019cc30, 0xc000431304, 0x5, 0xc00026ba10)
	github.com/elves/elvish/pkg/edit/completion.go:521 +0x71
github.com/elves/elvish/pkg/edit/complete.generateCommands(0xc000431304, 0x5, 0x9dc018, 0xc00019cc30, 0xc000431304, 0x5, 0xc000277800, 0x0, 0xc0002777e8)
	github.com/elves/elvish/pkg/edit/complete/generators.go:76 +0x1f4
github.com/elves/elvish/pkg/edit/complete.completeCommand(0x9d77a0, 0xc0004706c0, 0x9dc018, 0xc00019cc30, 0xc00026b710, 0xc000088b40, 0x0, 0xc0002777a0, 0x93eb28, 0xd, ...)
	github.com/elves/elvish/pkg/edit/complete/completers.go:93 +0x309
github.com/elves/elvish/pkg/edit/complete.Complete(0xc000431304, 0x5, 0x5, 0x9dc018, 0xc00019cc30, 0xc00026b710, 0xc000088b40, 0x0, 0x0, 0xc000088b40)
	github.com/elves/elvish/pkg/edit/complete/complete.go:90 +0x2b0
github.com/elves/elvish/pkg/edit.completionStart(0x9dcf38, 0xc0002080e0, 0x9cf940, 0xc00018b4a0, 0x9dc018, 0xc00019cc30, 0xc00026b710, 0xc000088b40, 0xc000186b01)
	github.com/elves/elvish/pkg/edit/completion.go:163 +0xf5
github.com/elves/elvish/pkg/edit.initCompletion.func4()
	github.com/elves/elvish/pkg/edit/completion.go:241 +0xaa
reflect.Value.call(0x88b5e0, 0xc00018b4d0, 0x13, 0x93aebc, 0x4, 0x0, 0x0, 0x0, 0xc00, 0x20300000000000, ...)
	reflect/value.go:476 +0x8e7
reflect.Value.Call(0x88b5e0, 0xc00018b4d0, 0x13, 0x0, 0x0, 0x0, 0x40f75b, 0x6400000000, 0xc000186ea0)
	reflect/value.go:337 +0xb9
github.com/elves/elvish/pkg/eval.(*goFn).Call(0xc00022b5e0, 0xc0002337a0, 0x0, 0x0, 0x0, 0xc00018a780, 0xc000310660, 0x3)
	github.com/elves/elvish/pkg/eval/go_fn.go:237 +0x678
github.com/elves/elvish/pkg/eval.(*Evaler).Call(0xc00019cc30, 0x9cec80, 0xc00022b5e0, 0x0, 0x0, 0x0, 0xc00018a780, 0x93ff09, 0x10, 0xc000310660, ...)
	github.com/elves/elvish/pkg/eval/eval.go:491 +0x273
github.com/elves/elvish/pkg/edit.callWithNotifyPorts(0x9d42b0, 0xc000053780, 0xc00019cc30, 0x9cec80, 0xc00022b5e0, 0x0, 0x0, 0x0)
	github.com/elves/elvish/pkg/edit/key_binding.go:67 +0x1d2
github.com/elves/elvish/pkg/edit.mapBinding.Handle(0x9d42b0, 0xc000053780, 0xc00019cc30, 0xc000198438, 0x1, 0x1, 0x9cf880, 0xc0002c4ba8, 0x40d44f)
	github.com/elves/elvish/pkg/edit/key_binding.go:41 +0x1c5
github.com/elves/elvish/pkg/cli.(*codeArea).handleKeyEvent(0xc00022c000, 0x9, 0xc000208100)
	github.com/elves/elvish/pkg/cli/codearea.go:289 +0x10e
github.com/elves/elvish/pkg/cli.(*codeArea).Handle(0xc00022c000, 0x9cf880, 0xc0002c4ba0, 0x0)
	github.com/elves/elvish/pkg/cli/codearea.go:164 +0xc5
github.com/elves/elvish/pkg/cli.(*app).handle(0xc0002080e0, 0x8e8660, 0xc0002c4ba0)
	github.com/elves/elvish/pkg/cli/app.go:171 +0x2b6
github.com/elves/elvish/pkg/cli.(*loop).Run(0xc000196d40, 0xc0001ca101, 0xc000044660, 0xc0002080e0, 0xc0002c48b0)
	github.com/elves/elvish/pkg/cli/loop.go:129 +0x16f
github.com/elves/elvish/pkg/cli.(*app).ReadCode(0xc0002080e0, 0x0, 0x0, 0x0, 0x0)
	github.com/elves/elvish/pkg/cli/app.go:334 +0x3f9
github.com/elves/elvish/pkg/edit.(*Editor).ReadCode(0xc000053780, 0xc000010020, 0x9cebe0, 0xc00050c8e8, 0xc00011a418)
	github.com/elves/elvish/pkg/edit/editor.go:99 +0x33
github.com/elves/elvish/pkg/shell.Interact(0xc000010010, 0xc000010018, 0xc000010020, 0xc000187ca8)
	github.com/elves/elvish/pkg/shell/interact.go:81 +0x3b0
github.com/elves/elvish/pkg/shell.program.Run(0xc000010010, 0xc000010018, 0xc000010020, 0xc0001f32d0, 0xc0000201f0, 0x0, 0x0, 0xc92c40, 0xc000187f68)
	github.com/elves/elvish/pkg/shell/shell.go:40 +0x2de
github.com/elves/elvish/pkg/prog.Run(0xc000010010, 0xc000010018, 0xc000010020, 0xc0000201f0, 0x1, 0x1, 0xc000187f38, 0x4, 0x4, 0x0)
	github.com/elves/elvish/pkg/prog/prog.go:136 +0x258
main.main()
	github.com/elves/elvish/cmd/withweb/elvish/main.go:16 +0x145

goroutine 18 [chan receive, 50 minutes]:
github.com/elves/elvish/pkg/eval.getBlackholeChan.func1(0xc0001ca060)
	github.com/elves/elvish/pkg/eval/port.go:67 +0x47
created by github.com/elves/elvish/pkg/eval.getBlackholeChan
	github.com/elves/elvish/pkg/eval/port.go:66 +0x58

goroutine 19 [syscall]:
os/signal.signal_recv(0x9d5200)
	runtime/sigqueue.go:168 +0xa5
os/signal.loop()
	os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x45

goroutine 7 [chan receive]:
github.com/elves/elvish/pkg/shell.setupShell.func1(0xc0001883c0, 0xc000010010, 0xc000010018, 0xc000010020)
	github.com/elves/elvish/pkg/shell/shell.go:51 +0xa5
created by github.com/elves/elvish/pkg/shell.setupShell
	github.com/elves/elvish/pkg/shell/shell.go:50 +0xf9

goroutine 21 [chan receive]:
github.com/elves/elvish/pkg/cli/prompt.(*Prompt).loop(0xc0001f3f80)
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:77 +0xc8
created by github.com/elves/elvish/pkg/cli/prompt.New
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:70 +0x165

goroutine 22 [chan receive]:
github.com/elves/elvish/pkg/cli/prompt.(*Prompt).loop(0xc00022a070)
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:77 +0xc8
created by github.com/elves/elvish/pkg/cli/prompt.New
	github.com/elves/elvish/pkg/cli/prompt/prompt.go:70 +0x165

runtime error: invalid memory address or nil pointer dereference

Execing recovery shell /bin/sh
```

**Comment by krader1961** [comment]
I can't reproduce using Elvish built from HEAD:

```
> use edit
Exception: no such module: edit
[tty 1], line 1: use edit
```

So apparently this has already been fixed. As an FYI, given how rapidly Elvish is changing it's usually a good idea to try to reproduce a problem using the [latest binary](https://elv.sh/get/) or build from source that is synced to the Github master branch.

**Comment by crinklywrappr** [comment]
I am certainly willing to try building and running `master`, but I will either need to find some time to set up a VM, or get some instructions on building w/ nix.

I will try the binary, though.

**Comment by krader1961** [comment]
> The pre-built binary does not work on NixOS.

Did you download the correct binary? It looks like you downloaded the ARM 64-bit binary. Is that the architecture of your system?

**Comment by crinklywrappr** [comment]
Oh dear.  That's embarassing.

The levenshtein distance between arm64 and amd64 is pretty small but still....

Thanks for pointing this out - I will rerun both tickets and update the ticket.

**Comment by crinklywrappr** [comment]
I am able to reproduce the crash using `elvish-HEAD` 👍🏻

**Comment by krader1961** [comment]
I can also reproduce this bug on macOS using Elvish built from the master branch. When I first read the issue I didn't understand that you have to `use edit` before attempting to resolve a command (or var) in that namespace in order to reproduce the bug. For example, it is sufficient to interactively execute `use edit` then type `edit:add-var` followed by Enter. This looks like a case of the `edit` namespace being implicitly instantiated in a magical manner for interactive shells that is incompatible with the usual `use` command behavior.

**Comment by xiaq** [comment]
Seems that this no longer reproduces.

There is a still bug - if you do `use edit:`, which correctly throws a bug, `edit:` will become an empty namespace. This bug is tracked in #1445.

**Comment by krader1961** [comment]
I'm still confused why `use edit` isn't allowed interactively and treated as a no-op (since the module has already been implicitly "used" and cached) rather than instantiating an empty namespace. An analogy is `use builtin`. Yes, it isn't imported implicitly (although one could argue it should be since it's no less magical than `edit`) but you can safely `use builtin` more than once. Also, I could swear there was an issue asking that `use edit` be allowed in non-interactive shells although I can't find it now.

**Comment by xiaq** [comment]
That is #1299.

The weirdness of the namespace is an implementation artifact and shouldn't be hard to fix.
