### ISSUE TITLE
Crash in REPL in malformed `for` loop

### ISSUE THREAD

**Issue by hashier** [elves/elvish#1456]
The following code crashes the REPL.

```elvish
for i [1 2 3] {|d| echo $d }
```

Stacktrace:
```
~ $ elvish
~> for i [1 2 3] {|d| echo $d }

goroutine 1 [running]:
src.elv.sh/pkg/sys.DumpStack()
	src.elv.sh/pkg/sys/dumpstack.go:10 +0x66
src.elv.sh/pkg/shell.handlePanic()
	src.elv.sh/pkg/shell/interact.go:144 +0x5a
panic({0x43ef1c0, 0xc00064e600})
	runtime/panic.go:1038 +0x215
src.elv.sh/pkg/eval.(*forOp).exec.func1({0x43cacc0, 0xc0006147b0})
	src.elv.sh/pkg/eval/builtin_special.go:652 +0xfe
src.elv.sh/pkg/eval/vals.Iterate({0x443be80, 0xc00064e4e0}, 0xc000612ec0)
	src.elv.sh/pkg/eval/vals/iterate.go:40 +0x16b
src.elv.sh/pkg/eval.(*forOp).exec(0xc000650090, 0xc00064c8c0)
	src.elv.sh/pkg/eval/builtin_special.go:643 +0x2a5
src.elv.sh/pkg/eval.(*formOp).exec(0xc000640370, 0xc00064c8c0)
	src.elv.sh/pkg/eval/compile_effect.go:341 +0x2b9
src.elv.sh/pkg/eval.(*pipelineOp).exec.func1({0x44e1a40, 0xc000640370}, 0xc000614900)
	src.elv.sh/pkg/eval/compile_effect.go:120 +0x5a
src.elv.sh/pkg/eval.(*pipelineOp).exec(0xc000612e80, 0xc00064c850)
	src.elv.sh/pkg/eval/compile_effect.go:134 +0x692
src.elv.sh/pkg/eval.chunkOp.exec({{0x0, 0x1c}, {0xc000614760, 0x1, 0x1}}, 0xc00060a828)
	src.elv.sh/pkg/eval/compile_effect.go:32 +0x112
src.elv.sh/pkg/eval.nsOp.prepare.func1()
	src.elv.sh/pkg/eval/compiler.go:81 +0x26
src.elv.sh/pkg/eval.(*Evaler).Eval(0xc000292000, {{0xc000629518, 0x7}, {0xc000514100, 0x1c}, 0x0}, {{0xc00060a828, 0x3, 0x3}, 0x447e430, ...})
	src.elv.sh/pkg/eval/eval.go:408 +0x5a4
src.elv.sh/pkg/shell.evalInTTY(0x1, {0xc00011a000, 0xc00011a008, 0xc00011a010}, {{0xc000629518, 0x7}, {0xc000514100, 0x1c}, 0x0})
	src.elv.sh/pkg/shell/shell.go:133 +0x185
src.elv.sh/pkg/shell.interact(0xc000292000, {0xc00011a000, 0xc00011a008, 0xc00011a010}, 0xc0000abd18)
	src.elv.sh/pkg/shell/interact.go:130 +0xd9d
src.elv.sh/pkg/shell.Program.Run({0x47b1100}, {0xc00011a000, 0xc00011a008, 0xc00011a010}, 0xc000286f50, {0xc0001101c0, 0x2, 0x0})
	src.elv.sh/pkg/shell/shell.go:72 +0x2de
src.elv.sh/pkg/prog.compositeProgram.Run({0xc00009eb70, 0x3, 0xc0000abe40}, {0xc00011a000, 0xc00011a008, 0xc00011a010}, 0x411556f, {0xc0001101c0, 0x0, 0x0})
	src.elv.sh/pkg/prog/prog.go:154 +0xd3
src.elv.sh/pkg/prog.Run({0xc00011a000, 0xc00011a008, 0xc00011a010}, {0xc0001101c0, 0x1, 0x1}, {0x44e2d80, 0xc0000ac120})
	src.elv.sh/pkg/prog/prog.go:128 +0x406
main.main()
	src.elv.sh/cmd/elvish/main.go:17 +0x116

goroutine 20 [chan receive]:
src.elv.sh/pkg/eval.getBlackholeChan.func1()
	src.elv.sh/pkg/eval/port.go:96 +0x3a
created by src.elv.sh/pkg/eval.getBlackholeChan
	src.elv.sh/pkg/eval/port.go:95 +0x6f

goroutine 21 [syscall]:
os/signal.signal_recv()
	runtime/sigqueue.go:166 +0x28
os/signal.loop()
	os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2c

goroutine 23 [chan receive]:
src.elv.sh/pkg/shell.initTTYAndSignal.func1()
	src.elv.sh/pkg/shell/shell.go:117 +0x86
created by src.elv.sh/pkg/shell.initTTYAndSignal
	src.elv.sh/pkg/shell/shell.go:116 +0x9f

goroutine 25 [chan receive]:
src.elv.sh/pkg/cli/prompt.(*Prompt).loop(0xc0002ae000)
	src.elv.sh/pkg/cli/prompt/prompt.go:77 +0xb6
created by src.elv.sh/pkg/cli/prompt.New
	src.elv.sh/pkg/cli/prompt/prompt.go:70 +0x1cf

goroutine 26 [chan receive]:
src.elv.sh/pkg/cli/prompt.(*Prompt).loop(0xc0002ae0e0)
	src.elv.sh/pkg/cli/prompt/prompt.go:77 +0xb6
created by src.elv.sh/pkg/cli/prompt.New
	src.elv.sh/pkg/cli/prompt/prompt.go:70 +0x1cf

interface conversion: errs.ArityMismatch is not eval.Exception: missing method Reason

Execing recovery shell /bin/sh
sh-3.2$
```

**Comment by zQueal** [comment]
confirmed with `0.18.0-dev.95baad069e3939c0eb059518ee55224f624e01f9`.

**Comment by zQueal** [comment]
```elvish-transcript
~
❯ elvish --version
0.18.0-dev.unknown

~
❯ for i [1 2 3] {|d| echo $d }
compilation error: 14-28 in [tty]: for body must not have arguments
compilation error: for body must not have arguments
[tty 2], line 1: for i [1 2 3] {|d| echo $d }
```

👌
