### ISSUE TITLE
Crash during tab completion

### ISSUE THREAD

**Issue by rsteube** [elves/elvish#1668]
version: v0.19.2

Things work really fine, but just got one specific completion that causes a crash.

```go
goroutine 1 [running]:
src.elv.sh/pkg/sys.DumpStack()
	src.elv.sh/pkg/sys/dumpstack.go:10 +0x66
src.elv.sh/pkg/shell.handlePanic()
	src.elv.sh/pkg/shell/interact.go:137 +0x5a
panic({0x7761c0, 0xc0004800a8})
	runtime/panic.go:884 +0x213
src.elv.sh/pkg/cli/tk.croppedLines.Render({{0xc000497470, 0x1, 0x1}, 0x0, 0x0, 0x1, 0x1}, 0x0, 0xc0004235e8?)
	src.elv.sh/pkg/cli/tk/listbox.go:257 +0x87c
src.elv.sh/pkg/cli/tk.(*listBox).renderHorizontal(0xc0000c0240, 0x93, 0x1)
	src.elv.sh/pkg/cli/tk/listbox.go:156 +0x3df
src.elv.sh/pkg/cli/tk.(*listBox).Render(0x93?, 0x21?, 0x0?)
	src.elv.sh/pkg/cli/tk/listbox.go:83 +0x1f
src.elv.sh/pkg/cli/tk.(*comboBox).Render(0xc0002ba640, 0x3?, 0x2)
	src.elv.sh/pkg/cli/tk/combobox.go:51 +0x63
src.elv.sh/pkg/cli.renderApp({0xc00030e8c0?, 0x2, 0x0?}, 0xc000384e60?, 0x742de0?)
	src.elv.sh/pkg/cli/app.go:306 +0xb6
src.elv.sh/pkg/cli.(*app).redraw(0xc0001ba300, 0x0)
	src.elv.sh/pkg/cli/app.go:277 +0x516
src.elv.sh/pkg/cli.(*loop).Run(0xc0001fe400)
	src.elv.sh/pkg/cli/loop.go:123 +0x51
src.elv.sh/pkg/cli.(*app).ReadCode(0xc0001ba300)
	src.elv.sh/pkg/cli/app.go:478 +0x49a
src.elv.sh/pkg/edit.(*Editor).ReadCode(0xc0000a6000?)
	src.elv.sh/pkg/edit/editor.go:121 +0x22
src.elv.sh/pkg/shell.interact(0xc000116000, {0xc0000a6000, 0xc0000a6008, 0xc0000a6010}, 0xc0001e3ce8)
	src.elv.sh/pkg/shell/interact.go:96 +0x849
src.elv.sh/pkg/shell.(*Program).Run(0xc0000a3ec0, {0xc0000a6000, 0xc0000a6008, 0xc0000a6010}, {0xc00009e010, 0x0, 0x0})
	src.elv.sh/pkg/shell/shell.go:85 +0x27a
src.elv.sh/pkg/prog.composite.Run({0xc0000abb00?, 0x4, 0x51c28f?}, {0xc0000a6000, 0xc0000a6008, 0xc0000a6010}, {0xc00009e010, 0x0, 0x0})
	src.elv.sh/pkg/prog/prog.go:117 +0x139
src.elv.sh/pkg/prog.Run({0xc0000a6000, 0xc0000a6008, 0xc0000a6010}, {0xc00009e010, 0x1, 0x1}, {0x822060, 0xc0000b2558})
	src.elv.sh/pkg/prog/prog.go:84 +0x4d7
main.main()
	src.elv.sh/cmd/elvish/main.go:18 +0x17f

goroutine 18 [chan receive]:
src.elv.sh/pkg/eval.getBlackholeChan.func1()
	src.elv.sh/pkg/eval/port.go:96 +0x3a
created by src.elv.sh/pkg/eval.getBlackholeChan
	src.elv.sh/pkg/eval/port.go:95 +0x6a

goroutine 19 [syscall]:
os/signal.signal_recv()
	runtime/sigqueue.go:152 +0x2f
os/signal.loop()
	os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2a

goroutine 5 [chan receive]:
src.elv.sh/pkg/shell.initSignal.func1()
	src.elv.sh/pkg/shell/shell.go:151 +0x85
created by src.elv.sh/pkg/shell.initSignal
	src.elv.sh/pkg/shell/shell.go:150 +0x91

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x7f11dc511f58, 0x72)
	runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc00010c080?, 0xc00013b000?, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00010c080, {0xc00013b000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc00010c080, {0xc00013b000?, 0x717640?, 0xc00028edc0?})
	net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000012028, {0xc00013b000?, 0xc00028edc0?, 0xc00024bc80?})
	net/net.go:183 +0x45
bufio.(*Reader).Read(0xc000034120, {0xc000026160, 0x1, 0xc00024bd70?})
	bufio/bufio.go:237 +0x1bb
io.ReadAtLeast({0x81fa60, 0xc000034120}, {0xc000026160, 0x1, 0x9}, 0x1)
	io/io.go:332 +0x9a
io.ReadFull(...)
	io/io.go:351
encoding/gob.decodeUintReader({0x81fa60?, 0xc000034120?}, {0xc000026160?, 0x9?, 0x9?})
	encoding/gob/decode.go:116 +0x57
encoding/gob.(*Decoder).recvMessage(0xc00010c280)
	encoding/gob/decoder.go:82 +0x39
encoding/gob.(*Decoder).decodeTypeSequence(0xc00010c280, 0x0)
	encoding/gob/decoder.go:148 +0x4f
encoding/gob.(*Decoder).DecodeValue(0xc00010c280, {0x70de80?, 0xc0000a3f80?, 0x7f11dc507728?})
	encoding/gob/decoder.go:227 +0x18f
encoding/gob.(*Decoder).Decode(0xc00010c280, {0x70de80?, 0xc0000a3f80?})
	encoding/gob/decoder.go:204 +0x165
src.elv.sh/pkg/rpc.(*gobClientCodec).ReadResponseHeader(0x731ec0?, 0x70bf80?)
	src.elv.sh/pkg/rpc/client.go:227 +0x27
src.elv.sh/pkg/rpc.(*Client).input(0xc0000341e0)
	src.elv.sh/pkg/rpc/client.go:108 +0xb4
created by src.elv.sh/pkg/rpc.NewClientWithCodec
	src.elv.sh/pkg/rpc/client.go:205 +0xc5

goroutine 21 [chan receive]:
src.elv.sh/pkg/cli/prompt.(*Prompt).loop(0xc0001eb730)
	src.elv.sh/pkg/cli/prompt/prompt.go:77 +0xb6
created by src.elv.sh/pkg/cli/prompt.New
	src.elv.sh/pkg/cli/prompt/prompt.go:70 +0x1bc

goroutine 22 [chan receive]:
src.elv.sh/pkg/cli/prompt.(*Prompt).loop(0xc0001eb810)
	src.elv.sh/pkg/cli/prompt/prompt.go:77 +0xb6
created by src.elv.sh/pkg/cli/prompt.New
	src.elv.sh/pkg/cli/prompt/prompt.go:70 +0x1bc

runtime error: index out of range [0] with length 0
```

**Comment by rsteube** [comment]
Seems to be an empty complexCandidate. Shouldn't cause a crash though.

**Comment by xiaq** [comment]
What's the code being completed?

**Comment by rsteube** [comment]
```elvish
set edit:completion:arg-completer[terramate] = {|@arg|
    echo '{"Usage":"","Messages":[],"DescriptionStyle":"dim white","Candidates":[{"Value":"","Display":"","Description":"","CodeSuffix":"","Style":"default"},{"Value":"narf","Display":"narf","Description":"","CodeSuffix":"","Style":"default"}]}' ^
		 | from-json | each {|completion|
		put $completion[Messages] | all (one) | each {|m|
			edit:notify (styled "error: " red)$m
		}
		if (not-eq $completion[Usage] "") {
			edit:notify (styled "usage: " $completion[DescriptionStyle])$completion[Usage]
		}
		put $completion[Candidates] | all (one) | each {|c|
			if (eq $c[Description] "") {
		    	edit:complex-candidate $c[Value] &display=(styled $c[Display] $c[Style]) &code-suffix=$c[CodeSuffix]
			} else {
		    	edit:complex-candidate $c[Value] &display=(styled $c[Display] $c[Style])(styled " " $completion[DescriptionStyle]" bg-default")(styled "("$c[Description]")" $completion[DescriptionStyle]) &code-suffix=$c[CodeSuffix]
			}
		}
    }
}
```

**Comment by xiaq** [comment]
Aha I see, as you pointed out it's a case of the code not handling candidates with an empty content correctly...

**Comment by xiaq** [comment]
Here is a minimal reproduction - you need two candidates to trigger the listing, and explicitly set the `&display` of the empty candidate:

```elvish-transcript
~> set edit:completion:arg-completer[foo] = {|@args|
     edit:complex-candidate '' &display=(styled '')
     edit:complex-candidate foo
   }
~> foo # press Tab here
```
