### ISSUE TITLE
Pass $nil to flag:parse crashes elvish

### ISSUE THREAD

**Issue by iandol** [elves/elvish#1869]
### What happened, and what did you expect to happen?

Try running `flag:parse $nil [[x $false 'test']]` and elvish crashes

```
ε ➪ flag:parse $nil [[x $false 'test']]

goroutine 1 [running]:
src.elv.sh/pkg/sys.DumpStack()
	src.elv.sh/pkg/sys/dumpstack.go:10 +0x64
src.elv.sh/pkg/shell.handlePanic()
	src.elv.sh/pkg/shell/interact.go:140 +0x44
panic({0x10270a2c0?, 0x1029a97b0?})
	runtime/panic.go:785 +0x124
src.elv.sh/pkg/eval/vals.ScanListToGo({0x0, 0x0}, {0x1026dfb80, 0x140003569d8})
	src.elv.sh/pkg/eval/vals/conversion.go:256 +0x2c
src.elv.sh/pkg/mods/flag.parse({0x0, 0x0}, {0x10277eef0, 0x1400072c960})
	src.elv.sh/pkg/mods/flag/flag.go:84 +0x5c
reflect.Value.call({0x10270be80?, 0x102776560?, 0x1400056b168?}, {0x10261079b, 0x4}, {0x1400072c9c0, 0x2, 0x1025a6534?})
	reflect/value.go:581 +0x97c
reflect.Value.Call({0x10270be80?, 0x102776560?, 0x1026de120?}, {0x1400072c9c0?, 0x102774740?, 0x14000120c40?})
	reflect/value.go:365 +0x94
src.elv.sh/pkg/eval.(*goFn).Call(0x140001a2380, 0x14000bd7b80, {0x14000d84ca0, 0x2, 0x1026fa140?}, 0x1400072c990)
	src.elv.sh/pkg/eval/go_fn.go:247 +0x870
src.elv.sh/pkg/eval.(*formOp).exec(0x14000120b60, 0x14000bd7b80, 0x1400056b5a0)
	src.elv.sh/pkg/eval/compile_effect.go:312 +0x2dc
src.elv.sh/pkg/eval.(*pipelineOp).exec.func1(0x140003568b8?, {0x0, 0x0, 0x0}, 0x14000679570)
	src.elv.sh/pkg/eval/compile_effect.go:137 +0x50
src.elv.sh/pkg/eval.(*pipelineOp).exec(0x14000ceebc0, 0x14000bd7b00)
	src.elv.sh/pkg/eval/compile_effect.go:153 +0x744
src.elv.sh/pkg/eval.(*chunkOp).exec(0x1400072c7e0, 0x14000bd7b00)
	src.elv.sh/pkg/eval/compile_effect.go:32 +0x64
src.elv.sh/pkg/eval.nsOp.prepare.func1()
	src.elv.sh/pkg/eval/compiler.go:77 +0x2c
src.elv.sh/pkg/eval.(*Evaler).Eval(0x1400009c000, {{0x14000eb6a37, 0x7}, {0x14000a86840, 0x23}, 0x0}, {{0x10277cb18, 0x14000a1e6e0}, {0x140003568b8, 0x3, ...}, ...})
	src.elv.sh/pkg/eval/eval.go:343 +0x3c4
src.elv.sh/pkg/shell.evalInTTY({0x1400005a058, 0x1400005a060, 0x1400005a068}, 0x1400009c000, {0x10277aa88, 0x140000d0b60}, {{0x14000eb6a37, 0x7}, {0x14000a86840, 0x23}, ...})
	src.elv.sh/pkg/shell/shell.go:191 +0x140
src.elv.sh/pkg/shell.interact(0x1400009c000, {0x1400005a058, 0x1400005a060, 0x1400005a068}, 0x14000195c90)
	src.elv.sh/pkg/shell/interact.go:127 +0x920
src.elv.sh/pkg/shell.(*Program).Run(0x140001a6240, {0x1400005a058, 0x1400005a060, 0x1400005a068}, {0x1400001e1a0, 0x0, 0x0})
	src.elv.sh/pkg/shell/shell.go:106 +0x1d4
src.elv.sh/pkg/prog.composite.Run({0x14000035880?, 0x14000195e18?, 0x10244ba7c?}, {0x1400005a058, 0x1400005a060, 0x1400005a068}, {0x1400001e1a0, 0x0, 0x0})
	src.elv.sh/pkg/prog/prog.go:192 +0xf0
src.elv.sh/pkg/prog.Run({0x1400005a058, 0x1400005a060, 0x1400005a068}, {0x1400001e1a0, 0x1, 0x1}, {0x10277a880, 0x1400000c558})
	src.elv.sh/pkg/prog/prog.go:158 +0x410
main.main()
	src.elv.sh/cmd/elvish/main.go:18 +0x150

goroutine 7 [chan receive]:
src.elv.sh/pkg/eval.getBlackholeChan.func1()
	src.elv.sh/pkg/eval/port.go:76 +0x38
created by src.elv.sh/pkg/eval.getBlackholeChan in goroutine 1
	src.elv.sh/pkg/eval/port.go:75 +0x6c

goroutine 8 [syscall]:
os/signal.signal_recv()
	runtime/sigqueue.go:149 +0x2c
os/signal.loop()
	os/signal/signal_unix.go:23 +0x1c
created by os/signal.Notify.func1.1 in goroutine 1
	os/signal/signal.go:151 +0x28

goroutine 17 [chan receive]:
src.elv.sh/pkg/shell.initSignal.func1()
	src.elv.sh/pkg/shell/shell.go:172 +0x78
created by src.elv.sh/pkg/shell.initSignal in goroutine 1
	src.elv.sh/pkg/shell/shell.go:171 +0x8c

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x1295fb078, 0x72)
	runtime/netpoll.go:351 +0xa0
internal/poll.(*pollDesc).wait(0x14000134d00?, 0x140001b9000?, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x14000134d00, {0x140001b9000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:165 +0x1fc
net.(*netFD).Read(0x14000134d00, {0x140001b9000?, 0x14000123c58?, 0x1024af874?})
	net/fd_posix.go:55 +0x28
net.(*conn).Read(0x1400005a550, {0x140001b9000?, 0x14000123be8?, 0x16?})
	net/net.go:189 +0x34
bufio.(*Reader).Read(0x140000724e0, {0x1400000ff30, 0x1, 0x10231b7f0?})
	bufio/bufio.go:241 +0x1b4
io.ReadAtLeast({0x102778be0, 0x140000724e0}, {0x1400000ff30, 0x1, 0x9}, 0x1)
	io/io.go:335 +0xa0
io.ReadFull(...)
	io/io.go:354
encoding/gob.decodeUintReader({0x102778be0, 0x140000724e0}, {0x1400000ff30, 0x9, 0x9})
	encoding/gob/decode.go:116 +0x4c
encoding/gob.(*Decoder).recvMessage(0x14000134f00)
	encoding/gob/decoder.go:82 +0x38
encoding/gob.(*Decoder).decodeTypeSequence(0x14000134f00, 0x0)
	encoding/gob/decoder.go:148 +0x50
encoding/gob.(*Decoder).DecodeValue(0x14000134f00, {0x1026d8260?, 0x14000090420?, 0x1024c1ea0?})
	encoding/gob/decoder.go:227 +0x174
encoding/gob.(*Decoder).Decode(0x14000134f00, {0x1026d8260?, 0x14000090420?})
	encoding/gob/decoder.go:204 +0x128
src.elv.sh/pkg/rpc.(*gobClientCodec).ReadResponseHeader(0x102706900?, 0x1026d7aa0?)
	src.elv.sh/pkg/rpc/client.go:227 +0x2c
src.elv.sh/pkg/rpc.(*Client).input(0x140000725a0)
	src.elv.sh/pkg/rpc/client.go:108 +0x98
created by src.elv.sh/pkg/rpc.NewClientWithCodec in goroutine 1
	src.elv.sh/pkg/rpc/client.go:205 +0xb4

goroutine 18 [chan receive]:
src.elv.sh/pkg/cli/prompt.(*Prompt).loop(0x140000d0fc0)
	src.elv.sh/pkg/cli/prompt/prompt.go:77 +0x9c
created by src.elv.sh/pkg/cli/prompt.New in goroutine 1
	src.elv.sh/pkg/cli/prompt/prompt.go:70 +0x190

goroutine 19 [chan receive]:
src.elv.sh/pkg/cli/prompt.(*Prompt).loop(0x140000d10a0)
	src.elv.sh/pkg/cli/prompt/prompt.go:77 +0x9c
created by src.elv.sh/pkg/cli/prompt.New in goroutine 1
	src.elv.sh/pkg/cli/prompt/prompt.go:70 +0x190

goroutine 1933 [select]:
src.elv.sh/pkg/eval.ListenInterrupts.func1()
	src.elv.sh/pkg/eval/interrupts.go:24 +0x68
created by src.elv.sh/pkg/eval.ListenInterrupts in goroutine 1
	src.elv.sh/pkg/eval/interrupts.go:23 +0xec

runtime error: invalid memory address or nil pointer dereference

Execing recovery shell /bin/sh
sh-3.2$ 
```

### Output of "elvish -version"

0.22.0-dev.0.20241122145032-9c07ef53e4b2+official

### Code of Conduct

- [X] I agree to follow Elvish's [Code of Conduct](https://src.elv.sh/CODE_OF_CONDUCT.md).

**Comment by xiaq** [comment]
I fixed the immediate issue, but there are likely many more builtins that accept arguments that are interfaces or pointers and don't guard against `nil` properly; for that I filed #1870.

**Comment by iandol** [comment]
confirmed fixed, thanks!
