### ISSUE TITLE
Crash on bad usage of unpack

### ISSUE THREAD

**Issue by hexchain** [elves/elvish#226]
```
$ elvish -c 's="11\n22\n33\n44"; echo $s | unpack'
panic: (util.Exception) (0x6af180,0xc4200d64d0)

goroutine 27 [running]:
panic(0x6af180, 0xc4200d64d0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/elves/elvish/util.Throw(0xa12bc0, 0xc4200d64c0)
	/tmp/yaourt-tmp-haochentong/aur-elvish-git/src/build/src/github.com/elves/elvish/util/exception.go:10 +0x7e
github.com/elves/elvish/eval.throwf(0x6ebb4b, 0x26, 0xc420107df0, 0x1, 0x1)
	/tmp/yaourt-tmp-haochentong/aur-elvish-git/src/build/src/github.com/elves/elvish/eval/util.go:18 +0x6b
github.com/elves/elvish/eval.unpack.func1(0xa14200, 0xc4200d64a0)
	/tmp/yaourt-tmp-haochentong/aur-elvish-git/src/build/src/github.com/elves/elvish/eval/builtin-fn.go:442 +0x1bf
github.com/elves/elvish/eval.(*EvalCtx).IterateInputs.func1(0xc4200e8240, 0xc4200d6458, 0xc4200d6480, 0xc4200d2a80)
	/tmp/yaourt-tmp-haochentong/aur-elvish-git/src/build/src/github.com/elves/elvish/eval/eval.go:407 +0x309
created by github.com/elves/elvish/eval.(*EvalCtx).IterateInputs
	/tmp/yaourt-tmp-haochentong/aur-elvish-git/src/build/src/github.com/elves/elvish/eval/eval.go:418 +0xa3
```

**Comment by xiaq** [comment]
Although this bug is no longer observable due to the fact that strings are now iterable and thus can be unpacked, it has been fixed.
