### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhsj** [elves/elvish#231]
I don't know how I trigger this...

```
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/elves/elvish/sys.DumpStack(0xc420376c30, 0x1)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/sys/dumpstack.go:7 +0x79
github.com/elves/elvish/run.rescue()
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/run/run.go:115 +0xd2
panic(0x6a8620, 0xc42000c110)
        /usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
github.com/elves/elvish/edit.(*Stylist).applyToTokens(0xc420377048, 0x6e224b, 0x2, 0xc, 0x20)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/stylist.go:21 +0xe0
github.com/elves/elvish/edit.(*Stylist).formHead(0xc420377048, 0xc4200f1920)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/stylist.go:57 +0xbd
github.com/elves/elvish/edit.(*Stylist).style(0xc420377048, 0xa146a0, 0xc4204e69c0)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/stylist.go:36 +0x13f
github.com/elves/elvish/edit.(*Stylist).style(0xc420377048, 0xa147c0, 0xc4200a1180)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/stylist.go:40 +0xf8
github.com/elves/elvish/edit.(*Stylist).style(0xc420377048, 0xa14520, 0xc4200f14a0)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/stylist.go:40 +0xf8
github.com/elves/elvish/edit.(*Editor).refresh(0xc4201082c0, 0x700000, 0xc42010835c, 0xc4203f56a0)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/editor.go:180 +0x380
github.com/elves/elvish/edit.(*Editor).finishReadLine(0xc4201082c0, 0xc420377838)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/editor.go:285 +0xf0
panic(0x6a8620, 0xc42000c110)
        /usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
github.com/elves/elvish/edit.(*Stylist).applyToTokens(0xc420377540, 0x6e224b, 0x2, 0xc, 0x20)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/stylist.go:21 +0xe0
github.com/elves/elvish/edit.(*Stylist).formHead(0xc420377540, 0xc4200f10e0)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/stylist.go:57 +0xbd
github.com/elves/elvish/edit.(*Stylist).style(0xc420377540, 0xa146a0, 0xc4204e6540)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/stylist.go:36 +0x13f
github.com/elves/elvish/edit.(*Stylist).style(0xc420377540, 0xa147c0, 0xc4200a0e00)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/stylist.go:40 +0xf8
github.com/elves/elvish/edit.(*Stylist).style(0xc420377540, 0xa14520, 0xc4200f0cc0)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/stylist.go:40 +0xf8
github.com/elves/elvish/edit.(*Editor).refresh(0xc4201082c0, 0x7f89cf8e0100, 0xc420180900, 0xc420100a70)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/editor.go:180 +0x380
github.com/elves/elvish/edit.(*Editor).ReadLine(0xc4201082c0, 0x0, 0x0, 0x0, 0x0)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/editor.go:342 +0x4d9
github.com/elves/elvish/run.interact.func1(0xa11b20, 0xc42053f580, 0x6e3c5a, 0xa)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/run/run.go:171 +0x2a
github.com/elves/elvish/run.interact(0xc4200f20c0, 0xc4200e8100)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/run/run.go:182 +0x1e8
github.com/elves/elvish/run.Main()
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/run/run.go:106 +0x23f
main.main()
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/main.go:8 +0x14

goroutine 17 [syscall, 18 minutes, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1

goroutine 20 [syscall]:
os/signal.signal_recv(0xa132e0)
        /usr/lib/go-1.7/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/lib/go-1.7/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/lib/go-1.7/src/os/signal/signal_unix.go:28 +0x41

goroutine 21 [select, 18 minutes, locked to thread]:
runtime.gopark(0x702238, 0x0, 0x6e2d1c, 0x6, 0x18, 0x2)
        /usr/lib/go-1.7/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc420023f30, 0x0, 0x18)
        /usr/lib/go-1.7/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc420023f30)
        /usr/lib/go-1.7/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /usr/lib/go-1.7/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
        /usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1

goroutine 22 [chan receive, 18 minutes]:
github.com/elves/elvish/run.handleHupAndQuit.func1(0xc420070240)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/run/run.go:235 +0x65
created by github.com/elves/elvish/run.handleHupAndQuit
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/run/run.go:241 +0x148

goroutine 34 [chan receive]:
github.com/elves/elvish/run.logSignals.func1(0xc4200703c0)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/run/run.go:225 +0x6a
created by github.com/elves/elvish/run.logSignals
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/run/run.go:228 +0x8a

goroutine 36 [syscall, 18 minutes]:
syscall.Syscall(0x0, 0x7, 0xc420077790, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x7, 0xc420077790, 0x1, 0x4, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0x7, 0xc420077790, 0x1, 0x4, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/syscall/syscall_unix.go:161 +0x49
os.(*File).read(0xc420100030, 0xc420077790, 0x1, 0x4, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/os/file_unix.go:228 +0x4f
os.(*File).Read(0xc420100030, 0xc420077790, 0x1, 0x4, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/os/file.go:101 +0x59
io.ReadAtLeast(0xa11ba0, 0xc420100030, 0xc420077790, 0x1, 0x4, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/io/io.go:307 +0xa4
io.ReadFull(0xa11ba0, 0xc420100030, 0xc420077790, 0x1, 0x4, 0x70017a, 0xc41fffc7db, 0x0)
        /usr/lib/go-1.7/src/io/io.go:325 +0x58
fmt.(*readRune).readByte(0xc420077770, 0xc420070420, 0x60, 0x58)
        /usr/lib/go-1.7/src/fmt/scan.go:328 +0xc7
fmt.(*readRune).ReadRune(0xc420077770, 0x0, 0x0, 0x700177, 0x700176)
        /usr/lib/go-1.7/src/fmt/scan.go:344 +0x3a
fmt.(*ss).ReadRune(0xc420070420, 0x30, 0x28, 0x6c7dc0, 0x550d5a)
        /usr/lib/go-1.7/src/fmt/scan.go:189 +0x81
fmt.(*ss).getRune(0xc420070420, 0x1)
        /usr/lib/go-1.7/src/fmt/scan.go:211 +0x2f
fmt.(*ss).skipSpace(0xc420070420, 0x0)
        /usr/lib/go-1.7/src/fmt/scan.go:427 +0x2f
fmt.(*ss).SkipSpace(0xc420070420)
        /usr/lib/go-1.7/src/fmt/scan.go:305 +0x30
fmt.(*ss).doScanf(0xc420070420, 0x6e221b, 0x2, 0xc420036f00, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/fmt/scan.go:1176 +0x358
fmt.Fscanf(0xa11ba0, 0xc420100030, 0x6e221b, 0x2, 0xc420036f00, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/fmt/scan.go:143 +0xc5
github.com/elves/elvish/stub.relaySignals(0xa11ba0, 0xc420100030, 0xc4200f01e0, 0xc4200f0240)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/stub/stub.go:140 +0xf7
created by github.com/elves/elvish/stub.NewStub
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/stub/stub.go:73 +0x6e9

goroutine 37 [syscall, 18 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x216c, 0xc420112000, 0x1000004, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc4200f2150, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/os/wait_waitid.go:28 +0xbc
os.(*Process).wait(0xc4200f2150, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/os/exec_unix.go:22 +0xab
os.(*Process).Wait(0xc4200f2150, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/os/doc.go:49 +0x2b
github.com/elves/elvish/stub.wait(0xc4200f2150, 0xc4200f02a0)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/stub/stub.go:159 +0x52
created by github.com/elves/elvish/stub.NewStub
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/stub/stub.go:74 +0x718

goroutine 38 [chan receive, 18 minutes]:
github.com/elves/elvish/run.Main.func2(0xc4200f21b0)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/run/run.go:92 +0x48
created by github.com/elves/elvish/run.Main
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/run/run.go:94 +0x198

goroutine 5711 [syscall]:
syscall.Syscall6(0x17, 0xa, 0xc4200e7e80, 0x0, 0x0, 0x0, 0x0, 0xc400000000, 0x463fec, 0xc4200d0000)
        /usr/lib/go-1.7/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.Select(0xa, 0xc4200e7e80, 0x0, 0x0, 0x0, 0xc4200e7e80, 0x2, 0xc420176e30)
        /usr/lib/go-1.7/src/syscall/zsyscall_linux_amd64.go:1411 +0xae
github.com/elves/elvish/sys.Select(0xa, 0xc4200e7e80, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/sys/select_linux.go:8 +0x53
github.com/elves/elvish/edit.(*AsyncReader).Run(0xc4200fa100)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/async-reader.go:70 +0x150
created by github.com/elves/elvish/edit.(*Reader).Run
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/reader.go:90 +0xa4

goroutine 5687 [select]:
github.com/elves/elvish/edit.(*Reader).Run(0xc4200fa140)
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/reader.go:93 +0x16c
created by github.com/elves/elvish/edit.(*Editor).ReadLine
        /home/zsj/Workspaces/go/src/github.com/elves/elvish/edit/editor.go:327 +0x23f

execing recovery shell /bin/sh
$ sh: turning off NDELAY mode
```

**Comment by zhsj** [comment]
OK, I find how to reproduce it.
Type `a=(dircolors /home/zsj/.dircolors)` first, not to execute it, since the syntax is wrong. Then move cursor after `(`, and hit `backspace` to delete `(`

**Comment by huiyiqun** [comment]
another example:

```
~> (ls) | each { echo $@ }
```

then move cursor after (, and hit backspace to delete it.

**Comment by huiyiqun** [comment]
more simple example:

```
~> (ls)
```

then delete the '('

**Comment by huiyiqun** [comment]
There seems two bugs, the first in `edit/stylist.go` and the second in `sys/dumpstack.go`.

**Comment by huiyiqun** [comment]
I'm wrong. sys/dumpstack.go works perfectly and print the stack, the only problem happened in edit/stylist.go.

**Comment by huiyiqun** [comment]
simplest method to reproduce:

```
~> a)
```

while

```
~> )
```

is safe

**Comment by zhsj** [comment]
Yep, unpaired brackets will trigger this bug, and `x}` also. But `x }` is safe.

**Comment by huiyiqun** [comment]
interesting

**Comment by zhsj** [comment]
also `x]`
