### ISSUE TITLE
Ctrl+RShift+\ crash elvish

### ISSUE THREAD

**Issue by themester** [elves/elvish#511]
this is the output
```"^\goroutine 18 [running]:
github.com/elves/elvish/sys.DumpStack(0xc4200786e0, 0xc42003cfa8)
	/home/mester/.go/src/github.com/elves/elvish/sys/dumpstack.go:7 +0xa7
github.com/elves/elvish/shell.handleSignals.func1(0xc42001c2a0)
	/home/mester/.go/src/github.com/elves/elvish/shell/shell.go:207 +0x191
created by github.com/elves/elvish/shell.handleSignals
	/home/mester/.go/src/github.com/elves/elvish/shell/shell.go:199 +0x8a

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc4204201ac)
	/usr/lib/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc4204201a0)
	/usr/lib/go/src/sync/waitgroup.go:131 +0x72
github.com/elves/elvish/eval.(*compiler).pipeline.func1(0xc4200a74a0)
	/home/mester/.go/src/github.com/elves/elvish/eval/compile_op.go:133 +0x5b3
github.com/elves/elvish/eval.Op.Exec(0xc420073bc0, 0x0, 0x15, 0xc4200a74a0)
	/home/mester/.go/src/github.com/elves/elvish/eval/compile_op.go:22 +0x48
github.com/elves/elvish/eval.(*compiler).chunk.func1(0xc4200a74a0)
	/home/mester/.go/src/github.com/elves/elvish/eval/compile_op.go:30 +0x64
github.com/elves/elvish/eval.Op.Exec(0xc4201a64a0, 0x0, 0x15, 0xc4200a74a0)
	/home/mester/.go/src/github.com/elves/elvish/eval/compile_op.go:22 +0x48
github.com/elves/elvish/eval.(*EvalCtx).PEval(0xc4200a74a0, 0xc4201a64a0, 0x0, 0x15, 0x0, 0x0)
	/home/mester/.go/src/github.com/elves/elvish/eval/eval.go:276 +0x8f
github.com/elves/elvish/eval.(*Evaler).eval(0xc4200950a0, 0xc4201a64a0, 0x0, 0x15, 0xc4201a64c0, 0x3, 0x3, 0x91dabd, 0xd, 0xc420304360, ...)
	/home/mester/.go/src/github.com/elves/elvish/eval/eval.go:159 +0x230
github.com/elves/elvish/eval.(*Evaler).EvalWithPorts(0xc4200950a0, 0xc4201a64c0, 0x3, 0x3, 0xc4201a64a0, 0x0, 0x15, 0x91dabd, 0xd, 0xc420304360, ...)
	/home/mester/.go/src/github.com/elves/elvish/eval/eval.go:231 +0x292
github.com/elves/elvish/eval.(*Evaler).Eval(0xc4200950a0, 0xc4201a64a0, 0x0, 0x15, 0x91dabd, 0xd, 0xc420304360, 0x15, 0x0, 0x0)
	/home/mester/.go/src/github.com/elves/elvish/eval/eval.go:187 +0x2f4
github.com/elves/elvish/eval.(*Evaler).SourceText(0xc4200950a0, 0x91dabd, 0xd, 0xc420304360, 0x15, 0x0, 0x0)
	/home/mester/.go/src/github.com/elves/elvish/eval/eval.go:347 +0x12f
github.com/elves/elvish/shell.sourceTextAndPrintError(0xc4200950a0, 0x91dabd, 0xd, 0xc420304360, 0x15, 0xc4201ca200)
	/home/mester/.go/src/github.com/elves/elvish/shell/shell.go:120 +0x53
github.com/elves/elvish/shell.interact(0xc4200950a0, 0xc42014ab10)
	/home/mester/.go/src/github.com/elves/elvish/shell/shell.go:187 +0x453
github.com/elves/elvish/shell.(*Shell).Run(0xc42012df10, 0xc4200101a0, 0x0, 0x0, 0x0)
	/home/mester/.go/src/github.com/elves/elvish/shell/shell.go:60 +0x1b8
main.main()
	/home/mester/.go/src/github.com/elves/elvish/main.go:156 +0x46f

goroutine 6 [syscall]:
os/signal.signal_recv(0xb82100)
	/usr/lib/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/lib/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 7 [chan receive, 2 minutes]:
github.com/elves/elvish/eval.init.2.func1()
	/home/mester/.go/src/github.com/elves/elvish/eval/port.go:56 +0x67
created by github.com/elves/elvish/eval.init.2
	/home/mester/.go/src/github.com/elves/elvish/eval/port.go:55 +0x49

goroutine 8 [IO wait]:
internal/poll.runtime_pollWait(0x7f943e548f70, 0x72, 0x0)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42011c198, 0x72, 0xffffffffffffff00, 0xb7fa80, 0xb7b678)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42011c198, 0xc42016a000, 0x1000, 0x1000)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42011c180, 0xc42016a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc42011c180, 0xc42016a000, 0x1000, 0x1000, 0x90d040, 0x849e40, 0x849e40)
	/usr/lib/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e540, 0xc42016a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:176 +0x6d
bufio.(*Reader).Read(0xc42005a2a0, 0xc4200149d1, 0x1, 0x9, 0xc420047ca8, 0x42b338, 0x93a308)
	/usr/lib/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0xb7cdc0, 0xc42005a2a0, 0xc4200149d1, 0x1, 0x9, 0x1, 0xc42001f300, 0xc42040e6d8, 0x182)
	/usr/lib/go/src/io/io.go:309 +0x86
io.ReadFull(0xb7cdc0, 0xc42005a2a0, 0xc4200149d1, 0x1, 0x9, 0xc420047d10, 0x405ddb, 0x3)
	/usr/lib/go/src/io/io.go:327 +0x58
encoding/gob.decodeUintReader(0xb7cdc0, 0xc42005a2a0, 0xc4200149d1, 0x9, 0x9, 0xc420047d88, 0x42ac79, 0xc400000008, 0xc420134180)
	/usr/lib/go/src/encoding/gob/decode.go:120 +0x63
encoding/gob.(*Decoder).recvMessage(0xc42011c380, 0xc420047da0)
	/usr/lib/go/src/encoding/gob/decoder.go:80 +0x57
encoding/gob.(*Decoder).decodeTypeSequence(0xc42011c380, 0x93bc00, 0xc42011c380)
	/usr/lib/go/src/encoding/gob/decoder.go:144 +0x14c
encoding/gob.(*Decoder).DecodeValue(0xc42011c380, 0x850ec0, 0xc42011e570, 0x16, 0x0, 0x0)
	/usr/lib/go/src/encoding/gob/decoder.go:212 +0xe6
encoding/gob.(*Decoder).Decode(0xc42011c380, 0x850ec0, 0xc42011e570, 0x0, 0x0)
	/usr/lib/go/src/encoding/gob/decoder.go:189 +0x16d
net/rpc.(*gobClientCodec).ReadResponseHeader(0xc42014ac00, 0xc42011e570, 0xc42040e6d8, 0x0)
	/usr/lib/go/src/net/rpc/client.go:223 +0x45
net/rpc.(*Client).input(0xc42005a360)
	/usr/lib/go/src/net/rpc/client.go:109 +0xb5
created by net/rpc.NewClientWithCodec
	/usr/lib/go/src/net/rpc/client.go:201 +0xc5

goroutine 9 [select, 1 minutes, locked to thread]:
runtime.gopark(0x93bbb0, 0x0, 0x91948d, 0x6, 0x18, 0x1)
	/usr/lib/go/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc420036f50, 0xc42001c360)
	/usr/lib/go/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
	/usr/lib/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 475 [syscall]:
syscall.Syscall6(0x3d, 0x69d2, 0xc420481a4c, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4201a6620)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.wait4(0x69d2, 0xc420481a4c, 0x2, 0x0, 0xc420481b80, 0x69d2, 0x0)
	/usr/lib/go/src/syscall/zsyscall_linux_amd64.go:163 +0x88
syscall.Wait4(0x69d2, 0xc420481aac, 0x2, 0x0, 0x3, 0xc420481b80, 0x69d2)
	/usr/lib/go/src/syscall/syscall_linux.go:255 +0x51
github.com/elves/elvish/eval.ExternalCmd.Call(0xc420304360, 0x6, 0xc4200a7540, 0xc4201a65e0, 0x2, 0x2, 0xc4201a40c0)
	/home/mester/.go/src/github.com/elves/elvish/eval/external_cmd.go:92 +0x4c2
github.com/elves/elvish/eval.(*ExternalCmd).Call(0xc420122260, 0xc4200a7540, 0xc4201a65e0, 0x2, 0x2, 0xc4201a40c0)
	<autogenerated>:1 +0x77
github.com/elves/elvish/eval.String.Call(0xc420304360, 0x6, 0xc4200a7540, 0xc4201a65e0, 0x2, 0x2, 0xc4201a40c0)
	/home/mester/.go/src/github.com/elves/elvish/eval/string.go:86 +0x89
github.com/elves/elvish/eval.(*String).Call(0xc420122220, 0xc4200a7540, 0xc4201a65e0, 0x2, 0x2, 0xc4201a40c0)
	<autogenerated>:1 +0x77
github.com/elves/elvish/eval.(*compiler).form.func3(0xc4200a7540)
	/home/mester/.go/src/github.com/elves/elvish/eval/compile_op.go:293 +0xb02
github.com/elves/elvish/eval.Op.Exec(0xc4204e40c0, 0x0, 0x15, 0xc4200a7540)
	/home/mester/.go/src/github.com/elves/elvish/eval/compile_op.go:22 +0x48
github.com/elves/elvish/eval.(*EvalCtx).PEval(0xc4200a7540, 0xc4204e40c0, 0x0, 0x15, 0x0, 0x0)
	/home/mester/.go/src/github.com/elves/elvish/eval/eval.go:276 +0x8f
github.com/elves/elvish/eval.(*compiler).pipeline.func1.1(0xc4200a7540, 0xc4204e40c0, 0x0, 0x15, 0xc42000e350, 0xc4204201a0, 0x0)
	/home/mester/.go/src/github.com/elves/elvish/eval/compile_op.go:91 +0x50
created by github.com/elves/elvish/eval.(*compiler).pipeline.func1
	/home/mester/.go/src/github.com/elves/elvish/eval/compile_op.go:90 +0x190

goroutine 474 [select]:
github.com/elves/elvish/eval.(*Evaler).EvalWithPorts.func1(0xc42001c660, 0xc4200950a0, 0xc42001c540, 0xc42001c5a0)
	/home/mester/.go/src/github.com/elves/elvish/eval/eval.go:216 +0xde
created by github.com/elves/elvish/eval.(*Evaler).EvalWithPorts
	/home/mester/.go/src/github.com/elves/elvish/eval/eval.go:212 +0x1ff

goroutine 473 [chan receive]:
github.com/elves/elvish/eval.(*Evaler).Eval.func1(0xc4201be360, 0xc4200950a0, 0xc42001c4e0)
	/home/mester/.go/src/github.com/elves/elvish/eval/eval.go:171 +0x134
created by github.com/elves/elvish/eval.(*Evaler).Eval
	/home/mester/.go/src/github.com/elves/elvish/eval/eval.go:170 +0xed```

**Comment by zzamboni** [comment]
I have the issue with master (as of today). In my case it can be triggered with `Ctrl-\` (any Ctrl key works, and also in combination with other keys, such as Shift or Alt). It doesn't seem to be a full crash (Elvish continues to run), but something inside it produces the message (The `_` shows where the cursor is after the message):
```
goroutine 9 [running]:
github.com/elves/elvish/sys.DumpStack(0xc42007e870, 0xc42003cfa8)
	/private/tmp/elvish-20171109-4839-lcua03/src/github.com/elves/elvish/sys/dumpstack.go:7 +0xa7
github.com/elves/elvish/shell.handleSignals.func1(0xc4201a0000)
	/private/tmp/elvish-20171109-4839-lcua03/src/github.com/elves/elvish/shell/shell.go:207 +0x191
created by github.com/elves/elvish/shell.handleSignals
	/private/tmp/elvish-20171109-4839-lcua03/src/github.com/elves/elvish/shell/shell.go:199 +0x8a

goroutine 1 [runnable]:
syscall.CloseOnExec(0x8)
	/usr/local/Cellar/go/1.9.2/libexec/src/syscall/exec_unix.go:96 +0x4c
os.Pipe(0x145e780, 0x10, 0xc42078cd80, 0xc420cd6d20)
	/usr/local/Cellar/go/1.9.2/libexec/src/os/pipe_bsd.go:23 +0x15d
github.com/elves/elvish/eval.pcaptureOutputInner(0xc420053670, 0xc420053568, 0xffffffffffffffff, 0xffffffffffffffff, 0xc420ae30e0, 0xc420ae30f0, 0xc420243680, 0xc42059b080)
	/private/tmp/elvish-20171109-4839-lcua03/src/github.com/elves/elvish/eval/compile_value.go:367 +0x8a
gi           _
ignored signal quit
```

**Comment by muesli** [comment]
Can confirm on master, too.

**Comment by chrispickard** [comment]
Ctrl+\ sends SIGQUIT.

Zsh and bash both ignore SIGQUIT, sh inserts it literally (as `^\`).

In RAW input mode elvish crashes rather than insert the character literally.

Elvish should probably trap SIGQUIT for parity with bash and zsh?

**Comment by xiaq** [comment]
Elvish catches SIGQUIT and prints the stack trace: https://github.com/elves/elvish/blob/c1b5e4d0cbb9bb2e78ab61e3802cd16b5a284cce/shell/shell.go#L207-L209

Elvish used to quit on SIGQUIT, but that is no longer the case on master.

**Comment by themester** [comment]
@xiaq why? I only want to close telnet console and I cannot do it

**Comment by xiaq** [comment]
@themester I am not sure what your question is. Elvish no longer quits on SIGQUIT, and I am not sure how this is related to telnet.
