### ISSUE TITLE
Elvish crashes in LASTCMD completion mode

### ISSUE THREAD

**Issue by SolitudeSF** [elves/elvish#577]
If you press any letter or symbol that is not M-1 or digits from completion it produces this result.
![2018-01-22 23 24 23](https://user-images.githubusercontent.com/10168645/35245207-6ee177f6-ffcb-11e7-88fc-bb67fe926921.png)
if you press M-1 again in this state elvish crashes with this output
```
runtime error: index out of range
goroutine 1 [running]:
github.com/elves/elvish/sys.DumpStack(0xc42004f2a8, 0x1)
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/sys/dumpstack.go:10 +0xa2
github.com/elves/elvish/program/shell.rescue()
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/program/shell/shell.go:59 +0xd2
panic(0x88e840, 0xbbe130)
        /usr/lib/go/src/runtime/panic.go:491 +0x283
github.com/elves/elvish/edit.(*lastcmd).Accept(...)
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/edit/lastcmd.go:83
github.com/elves/elvish/edit.lastcmdAltDefault(0xc4201d4000)
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/edit/lastcmd.go:104 +0x54a
github.com/elves/elvish/edit.(*Editor).CallFn(0xc4201d4000, 0xb92440, 0xc420189d20, 0x0, 0x0, 0x0)
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/edit/api.go:196 +0x545
github.com/elves/elvish/edit.(*Editor).ReadLine(0xc4201d4000, 0x0, 0x0, 0x0, 0x0)
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/edit/edit.go:458 +0xf8d
github.com/elves/elvish/program/shell.interact.func1(0x8a5900, 0xc42039e220, 0x16, 0x0)
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/program/shell/interact.go:41 +0x2f
github.com/elves/elvish/program/shell.interact(0xc420170150, 0xc42015e980, 0x16)
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/program/shell/interact.go:51 +0x1ff
github.com/elves/elvish/program/shell.(*Shell).Main(0xc420156c40, 0xc420010180, 0x0, 0x0, 0x0)
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/program/shell/shell.go:47 +0x19a
github.com/elves/elvish/program.Main(0xc420010180, 0x1, 0x1, 0x0)
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/program/program.go:118 +0x18a
main.main()
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/main.go:14 +0x45

goroutine 5 [syscall, 2 minutes]:
os/signal.signal_recv(0xb8f4c0)
        /usr/lib/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 18 [chan receive, 2 minutes]:
github.com/elves/elvish/eval.init.9.func1()
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/eval/port.go:60 +0x67
created by github.com/elves/elvish/eval.init.9
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/eval/port.go:59 +0x49

goroutine 22 [select, locked to thread]:
runtime.gopark(0x93fd50, 0x0, 0x91beea, 0x6, 0x18, 0x1)
        /usr/lib/go/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc42003ff50, 0xc420174180)
        /usr/lib/go/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
        /usr/lib/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 23 [chan receive, 2 minutes]:
github.com/elves/elvish/program/shell.handleSignals.func1(0xc4201740c0)
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/program/shell/shell.go:69 +0xdf
created by github.com/elves/elvish/program/shell.handleSignals
        /builddir/elvish-0.11/_build-elvish-xbps/src/github.com/elves/elvish/program/shell/shell.go:68 +0x8a

execing recovery shell /bin/sh
```
version is 0.11, not a devel build

**Comment by xiaq** [comment]
Good catch, thanks for reporting.

**Comment by xiaq** [comment]
This has been fixed \o/
