### ISSUE TITLE
Crash if edit:after-readline is not empty

### ISSUE THREAD

**Issue by notramo** [elves/elvish#589]
Arch Linux, `elvish-git` package from AUR.
version: 0.11-143-gcda0630b
kernel: Linux 4.14.15-1-ARCH
It crashes after accepting the command.
```
 ~ >>> ls

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/elves/elvish/sys.DumpStack(0xc420394d20, 0x1)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/sys/dumpstack.go:10 +0xa2
github.com/elves/elvish/program/shell.rescue()
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/program/shell/shell.go:59 +0xd2
panic(0x890740, 0xbc00a0)
	/usr/lib/go/src/runtime/panic.go:491 +0x283
github.com/elves/elvish/edit.(*editorRenderer).Render(0xc42020de60, 0xc4201a8cd0)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/render.go:238 +0x2e0
github.com/elves/elvish/edit/ui.Render(0xb8c440, 0xc42020de60, 0xb3, 0xb8e280)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/ui/render.go:16 +0x10d
github.com/elves/elvish/edit.(*editor).refresh(0xc420012280, 0x7fd59c540101, 0xc420388480, 0xc420503c20)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/edit.go:262 +0x2f3
github.com/elves/elvish/edit.(*editor).CallFn(0xc420012280, 0x7fd59c54b3f0, 0xc420388480, 0xc420503c20, 0x1, 0x1)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/api.go:135 +0x2bc
github.com/elves/elvish/edit.callHooks(0xc420012280, 0xb96420, 0xc42039ecc0, 0xc420503c20, 0x1, 0x1)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/hooks.go:49 +0x87
github.com/elves/elvish/edit.init.5.func1.2(0xc4204297b0, 0x2)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/hooks.go:28 +0xda
github.com/elves/elvish/edit.(*editor).finishReadLine(0xc420012280, 0x0, 0x0)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/edit.go:336 +0x255
github.com/elves/elvish/edit.(*editor).ReadLine.func1(0xc420012280)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/edit.go:349 +0x2f
github.com/elves/elvish/edit.(*editor).ReadLine(0xc420012280, 0xc4204297b0, 0x2, 0x0, 0x0)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/edit.go:509 +0x109f
github.com/elves/elvish/program/shell.interact.func1(0xc420094a10, 0xc420431a80, 0x0, 0x0)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/program/shell/interact.go:41 +0x2f
github.com/elves/elvish/program/shell.interact(0xc420094a10, 0xc42009a2c0, 0x13)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/program/shell/interact.go:51 +0x221
github.com/elves/elvish/program/shell.(*Shell).Main(0xc420174400, 0xc42006a160, 0x0, 0x0, 0x0)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/program/shell/shell.go:47 +0x19a
github.com/elves/elvish/program.Main(0xc42006a160, 0x1, 0x1, 0x0)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/program/program.go:118 +0x18a
main.main()
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/main.go:14 +0x45

goroutine 20 [syscall]:
os/signal.signal_recv(0xb91b40)
	/usr/lib/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/lib/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 22 [chan receive, 13 minutes]:
github.com/elves/elvish/eval.init.11.func1()
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/eval/port.go:58 +0x67
created by github.com/elves/elvish/eval.init.11
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/eval/port.go:57 +0x49

goroutine 7243 [IO wait]:
internal/poll.runtime_pollWait(0x7fd59c542c70, 0x72, 0x0)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4203ec118, 0x72, 0xffffffffffffff00, 0xb8f600, 0xb8a670)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4203ec118, 0xc4202b9000, 0x1000, 0x1000)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4203ec100, 0xc4202b9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc4203ec100, 0xc4202b9000, 0x1000, 0x1000, 0xc420001980, 0xc42003bb50, 0x43534f)
	/usr/lib/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc4202f6768, 0xc4202b9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:176 +0x6d
bufio.(*Reader).Read(0xc42032ade0, 0xc4205789e0, 0x1, 0x9, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0xb8bdc0, 0xc42032ade0, 0xc4205789e0, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:309 +0x86
io.ReadFull(0xb8bdc0, 0xc42032ade0, 0xc4205789e0, 0x1, 0x9, 0x0, 0x0, 0x3)
	/usr/lib/go/src/io/io.go:327 +0x58
encoding/gob.decodeUintReader(0xb8bdc0, 0xc42032ade0, 0xc4205789e0, 0x9, 0x9, 0xc420028d88, 0x42b1a9, 0xc400000008, 0xc420058dc0)
	/usr/lib/go/src/encoding/gob/decode.go:120 +0x63
encoding/gob.(*Decoder).recvMessage(0xc4203ec380, 0xc420028da0)
	/usr/lib/go/src/encoding/gob/decoder.go:80 +0x57
encoding/gob.(*Decoder).decodeTypeSequence(0xc4203ec380, 0x942800, 0xc4203ec380)
	/usr/lib/go/src/encoding/gob/decoder.go:144 +0x14c
encoding/gob.(*Decoder).DecodeValue(0xc4203ec380, 0x852c40, 0xc420376660, 0x16, 0x0, 0x0)
	/usr/lib/go/src/encoding/gob/decoder.go:212 +0xe6
encoding/gob.(*Decoder).Decode(0xc4203ec380, 0x852c40, 0xc420376660, 0x920601, 0xc420376660)
	/usr/lib/go/src/encoding/gob/decoder.go:189 +0x16d
net/rpc.(*gobClientCodec).ReadResponseHeader(0xc420376600, 0xc420376660, 0xc420066420, 0x9206ff)
	/usr/lib/go/src/net/rpc/client.go:223 +0x45
net/rpc.(*Client).input(0xc42032aea0)
	/usr/lib/go/src/net/rpc/client.go:109 +0xb5
created by net/rpc.NewClientWithCodec
	/usr/lib/go/src/net/rpc/client.go:201 +0xc5

goroutine 3 [select, locked to thread]:
runtime.gopark(0x9426e0, 0x0, 0x91c773, 0x6, 0x18, 0x1)
	/usr/lib/go/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc420038f50, 0xc420014180)
	/usr/lib/go/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
	/usr/lib/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 4 [chan receive]:
github.com/elves/elvish/program/shell.handleSignals.func1(0xc4200140c0)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/program/shell/shell.go:69 +0xdf
created by github.com/elves/elvish/program/shell.handleSignals
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/program/shell/shell.go:68 +0x8a

goroutine 7241 [chan receive]:
net/rpc.(*Client).Call(0xc42032aea0, 0xc420578a00, 0xd, 0x84ba00, 0xc420503c80, 0x84ba40, 0xc4205789c0, 0xc420481000, 0x3)
	/usr/lib/go/src/net/rpc/client.go:317 +0xbc
github.com/elves/elvish/daemon.(*Client).call(0xc42014ec00, 0x91bb43, 0x6, 0x84ba00, 0xc420503c80, 0x84ba40, 0xc4205789c0, 0x0, 0x0)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/daemon/client.go:82 +0x169
github.com/elves/elvish/daemon.(*Client).AddCmd(0xc42014ec00, 0xc4204297b0, 0x2, 0x2957, 0xc42032a780, 0xc420481000)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/daemon/client.go:122 +0xbe
github.com/elves/elvish/edit/history.(*Fuser).AddCmd(0xc42015d2c0, 0xc4204297b0, 0x2, 0x0, 0x0)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/history/fuser.go:35 +0xb5
github.com/elves/elvish/edit.(*hist).appendHistory.func1(0xc4200583c0, 0xc4204297b0, 0x2)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/history.go:141 +0x53
created by github.com/elves/elvish/edit.(*hist).appendHistory
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/history.go:140 +0x8d

execing recovery shell /bin/sh
sh-4.4$ 
```

**Comment by zzamboni** [comment]
Can you show the setup of `$edit:after-readline`? I use it all the time and have never experienced such a crash.

**Comment by zzamboni** [comment]
I take back my comment. After upgrading to master, I am getting the same behavior, reported in #591.

**Comment by zzamboni** [comment]
Some additional information: the problem disappears if I comment out all parts of my config that use the `$edit:after-readline` hooks (`$edit:before-readline` seems unaffected). This includes https://github.com/zzamboni/elvish-modules/blob/master/proxy.org, https://github.com/zzamboni/elvish-modules/blob/master/long-running-notifications.org, and the functions that set the terminal title before/after running commands.

**Comment by zzamboni** [comment]
Minimal example to trigger the bug (with an empty config):

```
~/.elvish> edit:after-readline = [ [l]{ nop } ]
~/.elvish> <press enter>

runtime error: invalid memory address or nil pointer dereference
...
```

The full log I get is at https://gist.github.com/c1b2ab5a059741b691a09bb4b4e7f01d
