### ISSUE TITLE
Runnning edit:redraw from interactive mode crashes Elvish

### ISSUE THREAD

**Issue by notramo** [elves/elvish#597]
os: Arch Linux, `elvish-git` package from AUR
version: 0.11-163-gb77b3d78
arch: x86_64
```
zsh% elvish
 ~ >>> edit:redraw
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7fb570]

goroutine 3843 [running]:
github.com/elves/elvish/eval.catch(0xc4201e7f58, 0xc420372540)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/eval/frame.go:173 +0x27a
panic(0x891c40, 0xbc20c0)
	/usr/lib/go/src/runtime/panic.go:491 +0x283
github.com/elves/elvish/edit.(*editorRenderer).Render(0xc4203a1ea0, 0xc4201ade50)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/render.go:238 +0x2e0
github.com/elves/elvish/edit/ui.Render(0xb8e440, 0xc4203a1ea0, 0xb3, 0xb90280)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/ui/render.go:16 +0x10d
github.com/elves/elvish/edit.(*editor).refresh(0xc42019e000, 0x460101, 0x1, 0xc4202f77e8)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/edit.go:265 +0x2f3
github.com/elves/elvish/edit.(*editor).redraw(0xc42019e000)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/insert.go:339 +0x32
github.com/elves/elvish/edit.(*editor).(github.com/elves/elvish/edit.redraw)-fm()
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/edit/insert.go:52 +0x2a
reflect.Value.call(0x860900, 0xc420180b30, 0x13, 0x91c16b, 0x4, 0x0, 0x0, 0x0, 0x86bbe0, 0x860900, ...)
	/usr/lib/go/src/reflect/value.go:434 +0x905
reflect.Value.Call(0x860900, 0xc420180b30, 0x13, 0x0, 0x0, 0x0, 0x0, 0x8ba260, 0xc420165900)
	/usr/lib/go/src/reflect/value.go:302 +0xa4
github.com/elves/elvish/eval.(*BuiltinFn).Call(0xc420165900, 0xc420372540, 0x0, 0x0, 0x0, 0xc4201a23c0, 0x0, 0xc420348000)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/eval/builtin_fn.go:190 +0x551
github.com/elves/elvish/eval.(*formOp).Invoke(0xc4202285b0, 0xc420372540, 0x0, 0x0)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/eval/compile_op.go:357 +0xb36
github.com/elves/elvish/eval.Op.Exec(0xb8e740, 0xc4202285b0, 0x0, 0xb, 0xc420372540, 0xc42013cff0, 0xc4203894d0)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/eval/compile_op.go:30 +0x4d
github.com/elves/elvish/eval.(*Frame).PEval(0xc420372540, 0xb8e740, 0xc4202285b0, 0x0, 0xb, 0x0, 0x0)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/eval/frame.go:120 +0xb2
github.com/elves/elvish/eval.(*pipelineOp).Invoke.func1(0xc420372540, 0xb8e740, 0xc4202285b0, 0x0, 0xb, 0xc4202fa7b0, 0xc42053e530, 0xc4202b5200)
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/eval/compile_op.go:117 +0x60
created by github.com/elves/elvish/eval.(*pipelineOp).Invoke
	/tmp/makepkg/elvish-git/src/build/src/github.com/elves/elvish/eval/compile_op.go:116 +0x18d
zsh% 
```

**Comment by xiaq** [comment]
This is now fixed.
