### ISSUE TITLE
Skip tests when pty open failed

### ISSUE THREAD

**Issue by zhsj** [elves/elvish#708]
During testing, I meet

```
--- FAIL: TestReadLine (0.00s)
panic: open /dev/pts/0: permission denied [recovered]
        panic: open /dev/pts/0: permission denied

goroutine 23 [running]:
testing.tRunner.func1(0xc42021a0f0)
        /usr/lib/go-1.10/src/testing/testing.go:742 +0x29d
panic(0x856880, 0xc4201f0930)
        /usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
github.com/elves/elvish/edit/edcore.run(0xc42013f0e0, 0xc4200e02a0, 0xc420219840, 0x27, 0x2d2, 0x4ed430)
        /<<BUILDDIR>>/elvish-0.12~rc1+ds1/obj-x86_64-linux-gnu/src/github.com/elves/elvish/edit/edcore/e2e_test.go:93 +0x145
github.com/elves/elvish/edit/edcore.TestReadLine(0xc42021a0f0)
        /<<BUILDDIR>>/elvish-0.12~rc1+ds1/obj-x86_64-linux-gnu/src/github.com/elves/elvish/edit/edcore/e2e_test.go:63 +0x13c
testing.tRunner(0xc42021a0f0, 0x901658)
        /usr/lib/go-1.10/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
        /usr/lib/go-1.10/src/testing/testing.go:824 +0x2e0
FAIL    github.com/elves/elvish/edit/edcore     0.011s
```

Can we skip this when `pty.Open` returns error, instead of panic? This is not elvish fault.

BTW, when I search `pty.Open` in test files, I found another test uses this, `edit/tty/setup_unix_test.go`. But I'm curious why this test doesn't run Linux?

**Comment by Xuanwo** [comment]
For the second problem, I think it's a typo: https://github.com/elves/elvish/blob/master/edit/tty/setup_unix_test.go#L1

The build tag should be `// +build !windows,!plan9` as in the `rune_reader_unix_test.go`
