### ISSUE TITLE
Crash when trying to cycle through completion candidates when there is none

### ISSUE THREAD

**Issue by SolitudeSF** [elves/elvish#717]
if you input something as filter and press tab elvish crashes with 
```
runtime error: index out of range
goroutine 1 [running]:
github.com/elves/elvish/sys.DumpStack(0xc4205c8918, 0x1)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/sys/d2
github.com/elves/elvish/program/shell.rescue()
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/progr5
panic(0x87f0e0, 0xbc02a0)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
github.com/elves/elvish/edit/completion.(*completion).selectedCandidate(...)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/4
github.com/elves/elvish/edit/completion.(*completion).Replacement(0xc42023c000, 0x975800, 0xc42023c000, 0x7fee4d4a8d68)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/9
github.com/elves/elvish/edit/edcore.(*editorRenderer).Render(0xc4204ee900, 0xc4203f20a0)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/b
github.com/elves/elvish/edit/ui.Render(0x971740, 0xc4204ee900, 0x77, 0x972680)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/b
github.com/elves/elvish/edit/edcore.(*editor).refresh(0xc4201e8000, 0x7fee4d420101, 0xc4203740a0, 0xc4203428c0)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/b
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc4201e8000, 0x7fee4d422040, 0xc4203740a0, 0xc4203428c0, 0x1, 0x)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/e
github.com/elves/elvish/edit/edcore.callHooks(0xc4201e8000, 0x9787c0, 0xc4202a2900, 0xc4203428c0, 0x1, 0x1)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/7
github.com/elves/elvish/edit/edcore.init.1.func1.2(0xc4204db178, 0x3)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/a
github.com/elves/elvish/edit/edcore.(*editor).finishReadLine(0xc4201e8000, 0x0, 0x0)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/6
github.com/elves/elvish/edit/edcore.(*editor).ReadLine.func1(0xc4201e8000)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/f
panic(0x87f0e0, 0xbc02a0)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
github.com/elves/elvish/edit/completion.(*completion).selectedCandidate(...)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/4
github.com/elves/elvish/edit/completion.(*completion).Replacement(0xc42023c000, 0x975800, 0xc42023c000, 0x7fee4d4a8d68)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/9
github.com/elves/elvish/edit/edcore.(*editorRenderer).Render(0xc420529d80, 0xc420352550)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/b
github.com/elves/elvish/edit/ui.Render(0x971740, 0xc420529d80, 0x77, 0x972680)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/b
github.com/elves/elvish/edit/edcore.(*editor).refresh(0xc4201e8000, 0x970101, 0xc420234500, 0x0)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/b
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc4201e8000, 0x9717c0, 0xc420234500, 0x0, 0x0, 0x0)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/e
github.com/elves/elvish/edit/edcore.(*editor).ReadLine(0xc4201e8000, 0x0, 0x0, 0x0, 0x0)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/f
github.com/elves/elvish/program/shell.interact.func1(0x896ea0, 0xc420504700, 0x16, 0x0)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/progrf
github.com/elves/elvish/program/shell.interact(0xc4200f5040, 0xc4200d2300, 0x16, 0x0)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/progr9
github.com/elves/elvish/program/shell.(*Shell).Main(0xc4201ca340, 0xc4200a2170, 0x0, 0x0, 0x0)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/progr7
github.com/elves/elvish/program.Main(0xc4200a2170, 0x1, 0x1, 0x0)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/progr0
main.main()
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/main.5

goroutine 19 [syscall]:
os/signal.signal_recv(0x975320)
        /usr/lib/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 21 [chan receive]:
github.com/elves/elvish/eval.init.13.func1()
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/eval/3
created by github.com/elves/elvish/eval.init.13
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/eval/9

goroutine 23 [select, locked to thread]:
runtime.gopark(0x937b88, 0x0, 0x910514, 0x6, 0x18, 0x1)
        /usr/lib/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc42004e750, 0xc420098300)
        /usr/lib/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
        /usr/lib/go/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2361 +0x1

goroutine 34 [chan receive]:
github.com/elves/elvish/program/shell.handleSignals.func1(0xc420098240)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/progr8
created by github.com/elves/elvish/program/shell.handleSignals
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/progrc

goroutine 50 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc42024a000)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/1
created by github.com/elves/elvish/edit/prompt.makePrompt
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/4

goroutine 51 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc42024a080)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/1
created by github.com/elves/elvish/edit/prompt.makePrompt
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/4

goroutine 2305 [syscall]:
syscall.Syscall6(0x10e, 0x7, 0xc420642280, 0x0, 0x0, 0x0, 0x0, 0x42add4, 0x937328, 0xc4201f1578)
        /usr/lib/go/src/syscall/asm_linux_amd64.s:44 +0x5
github.com/elves/elvish/vendor/golang.org/x/sys/unix.Pselect(0x7, 0xc420642280, 0x0, 0x0, 0x0, 0x0, 0xc42017e0f0, 0x0,)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/vendo2
github.com/elves/elvish/sys.Select(0x7, 0xc420642280, 0x0, 0x0, 0x2, 0xc4201f17c0)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/sys/s1
github.com/elves/elvish/sys.WaitForRead(0xc4201f16e8, 0x2, 0x2, 0x0, 0x1, 0x0, 0x0, 0x0)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/sys/w4
github.com/elves/elvish/edit/tty.(*runeReader).run(0xc42018c140)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/4
created by github.com/elves/elvish/edit/tty.(*runeReader).Start
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/f

goroutine 2354 [select]:
github.com/elves/elvish/edit/tty.(*reader).send(0xc420180240, 0x972560, 0xc420536008)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/d
github.com/elves/elvish/edit/tty.(*reader).run(0xc420180240)
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/f
created by github.com/elves/elvish/edit/tty.(*reader).Start
        /builddir/elvish-b24e4a73ccd948b8c08d4081c2bcfb7cf603a02b/_build-elvish-xbps/src/github.com/elves/elvish/edit/b

execing recovery shell /bin/sh
```

**Comment by kwshi** [comment]
I cannot seem to reproduce this problem.  Perhaps you can give more details on how to reproduce?

**Comment by SolitudeSF** [comment]
Start completion, input string that matches nothing, press tab.

**Comment by iwoloschin** [comment]
I'm also seeing this with 0.12-1-gb24e4a7.
