### ISSUE TITLE
dissoc crashes elvish with some maps

### ISSUE THREAD

**Issue by yrkv** [elves/elvish#762]
Using `dissoc` on maps approaching 20 entries causes the entire elvish process to crash. The amount does not seem to be consistent, I had one map crashing elvish at >18 entries and another at >16 entries.
```sh
~> elvish # create nested elvish process so we can see the error it creates
~> # create map with 16 entries
~> map = [&1=10 &2=10 &3=10 &4=10 &5=10 &6=10 &7=10 &8=10 &9=10 &10=10 &11=10 &12=10 &13=10 &14=10 &15=10 &16=10]
~> dissoc $map 1 # works fine
▶ [&10=10 &11=10 &12=10 &13=10 &14=10 &15=10 &16=10 &2=10 &3=10 &4=10 &5=10 &6=10 &7=10 &8=10 &9=10]
~> # create map with 17 entries
~> bad-map = [&1=10 &2=10 &3=10 &4=10 &5=10 &6=10 &7=10 &8=10 &9=10 &10=10 &11=10 &12=10 &13=10 &14=10 &15=10 &16=10 &17=10]
~> dissoc $bad-map 1 # crashes elvish completely
▶ panic: runtime error: index out of range

goroutine 276 [running]:
github.com/elves/elvish/vendor/github.com/xiaq/persistent/hashmap.(*bitmapNodeIterator).Elem(0xc0002a08e0, 0xc0001e4e70, 0x53a941, 0xc0002a0380, 0xc000352e00)
        /build/go/src/github.com/elves/elvish/vendor/github.com/xiaq/persistent/hashmap/hashmap.go:451 +0xbd
github.com/elves/elvish/vendor/github.com/xiaq/persistent/hashmap.(*arrayNodeIterator).Elem(0xc0002a0380, 0xc0002ce201, 0x2, 0x8000000000000002, 0xc0002ce276)
        /build/go/src/github.com/elves/elvish/vendor/github.com/xiaq/persistent/hashmap/hashmap.go:229 +0x34
github.com/elves/elvish/eval/vals.Repr(0x8d8740, 0xc0003ea9c0, 0x8000000000000000, 0x4, 0x0)
        /build/go/src/github.com/elves/elvish/eval/vals/repr.go:54 +0x3dc
github.com/elves/elvish/eval.relayChanToFile(0xc0001405a0, 0xc00000e018, 0x9306a2, 0x4, 0xc000026200)
        /build/go/src/github.com/elves/elvish/eval/std_ports.go:42 +0x93
created by github.com/elves/elvish/eval.newStdPorts
        /build/go/src/github.com/elves/elvish/eval/std_ports.go:26 +0xf9
Exception: elvish exited with 2
[tty], line 1: elvish # create nested elvish process so we can see the error it creates
~> # back at original elvish process
```

Can anyone verify that using `dissoc` on this map crashes elvish for you?

**Comment by xiaq** [comment]
This has been fixed. It was indeed a bug in the persistent hashmap library, a pretty subtle one nonetheless. Thanks for reporting!
