### ISSUE TITLE
Hitting Ctrl+n twice crashes elvish

### ISSUE THREAD

**Issue by srid** [elves/elvish#772]
# Environment 
elvish 0.12 on NixOS 18.09 (Thinkpad P71)

# Repro
1. Hit `Ctrl+n` to bring up the file manager
2. Immediately hit `Ctrl+n` again
3. Elvish will crash

# Crash log
```
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/elves/elvish/sys.DumpStack(0xc00039ca18, 0x1)
        /build/go/src/github.com/elves/elvish/sys/dumpstack.go:10 +0xa2
github.com/elves/elvish/program/shell.rescue()
        /build/go/src/github.com/elves/elvish/program/shell/shell.go:60 +0xc5
panic(0x8a4e80, 0xd0e280)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.11/share/go/src/runtime/panic.go:513 +0x1b9
github.com/elves/elvish/eval.catch(0xc00039d8a0, 0xc00016e300)
        /build/go/src/github.com/elves/elvish/eval/frame.go:190 +0x25f
panic(0x8a4e80, 0xd0e280)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.11/share/go/src/runtime/panic.go:513 +0x1b9
github.com/elves/elvish/edit/edcore.(*navigation).List(0xc0001afe00, 0x50, 0xc0001afe00, 0x7f1615319060)
        /build/go/src/github.com/elves/elvish/edit/edcore/navigation.go:346 +0x80
github.com/elves/elvish/edit/edcore.(*editorRenderer).Render(0xc00000c580, 0xc0002d60a0)
        /build/go/src/github.com/elves/elvish/edit/edcore/render.go:242 +0x10fd
github.com/elves/elvish/edit/ui.Render(0x9bb9e0, 0xc00000c580, 0x9e, 0x9bc8e0)
        /build/go/src/github.com/elves/elvish/edit/ui/render.go:16 +0x105
github.com/elves/elvish/edit/edcore.(*editor).refresh(0xc0001fe000, 0x9b0101, 0xc0001aff90, 0x0)
        /build/go/src/github.com/elves/elvish/edit/edcore/edit.go:268 +0x2c5
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc0001fe000, 0x9bba60, 0xc0001aff90, 0x0, 0x0, 0x0)
        /build/go/src/github.com/elves/elvish/edit/edcore/api.go:121 +0x24c
github.com/elves/elvish/edit/edcore.(*navigation).defaultFn(0xc0001afe00, 0xc0001fe000)
        /build/go/src/github.com/elves/elvish/edit/edcore/navigation.go:165 +0xbd
github.com/elves/elvish/edit/edcore.initNavigation.func4()
        /build/go/src/github.com/elves/elvish/edit/edcore/navigation.go:65 +0x33
reflect.Value.call(0x86f700, 0xc0001c9820, 0x13, 0x92fff6, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc0000c60d8, ...)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.11/share/go/src/reflect/value.go:447 +0x449
reflect.Value.Call(0x86f700, 0xc0001c9820, 0x13, 0x0, 0x0, 0x0, 0xc0000947e0, 0x48e08d, 0xc0000c4010)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.11/share/go/src/reflect/value.go:308 +0xa4
github.com/elves/elvish/eval.(*BuiltinFn).Call(0xc000204280, 0xc00016e300, 0x0, 0x0, 0x0, 0xc000170840, 0x90ee80, 0xc0004f1858)
        /build/go/src/github.com/elves/elvish/eval/builtin_fn.go:184 +0x5fc
github.com/elves/elvish/eval.(*Frame).Call(0xc00016e300, 0x9bba60, 0xc000204280, 0x0, 0x0, 0x0, 0xc000170840, 0x0, 0x0)
        /build/go/src/github.com/elves/elvish/eval/frame.go:143 +0xbb
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc0001fe000, 0x9bba60, 0xc000204280, 0x0, 0x0, 0x0)
        /build/go/src/github.com/elves/elvish/edit/edcore/api.go:115 +0x225
github.com/elves/elvish/edit/edcore.(*editor).ReadLine(0xc0001fe000, 0x0, 0x0, 0x0, 0x0)
        /build/go/src/github.com/elves/elvish/edit/edcore/edit.go:500 +0x95b
github.com/elves/elvish/program/shell.interact.func1(0x8bd560, 0xc0002ae0c0, 0x12, 0x0)
        /build/go/src/github.com/elves/elvish/program/shell/interact.go:41 +0x2f
github.com/elves/elvish/program/shell.interact(0xc00019a320, 0xc00018a060, 0x12, 0x0)
        /build/go/src/github.com/elves/elvish/program/shell/interact.go:51 +0x203
github.com/elves/elvish/program/shell.(*Shell).Main(0xc000176f80, 0xc0000b6170, 0x0, 0x0, 0x0)
        /build/go/src/github.com/elves/elvish/program/shell/shell.go:48 +0x1a7
github.com/elves/elvish/program.Main(0xc0000b6170, 0x1, 0x1, 0x0)
        /build/go/src/github.com/elves/elvish/program/program.go:119 +0x17e
main.main()
        /build/go/src/github.com/elves/elvish/main.go:14 +0x45

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.11/share/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.11/share/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.11/share/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 34 [chan receive]:
github.com/elves/elvish/eval.init.13.func1()
        /build/go/src/github.com/elves/elvish/eval/port.go:49 +0x53
created by github.com/elves/elvish/eval.init.13
        /build/go/src/github.com/elves/elvish/eval/port.go:48 +0x49

goroutine 22 [chan receive]:
github.com/elves/elvish/program/shell.handleSignals.func1(0xc00019e0c0)
        /build/go/src/github.com/elves/elvish/program/shell/shell.go:70 +0xb8
created by github.com/elves/elvish/program/shell.handleSignals
        /build/go/src/github.com/elves/elvish/program/shell/shell.go:69 +0x7c

goroutine 37 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc000188200)
        /build/go/src/github.com/elves/elvish/edit/prompt/prompt.go:76 +0xd1
created by github.com/elves/elvish/edit/prompt.makePrompt
        /build/go/src/github.com/elves/elvish/edit/prompt/prompt.go:69 +0x18f

goroutine 38 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc000188280)
        /build/go/src/github.com/elves/elvish/edit/prompt/prompt.go:76 +0xd1
created by github.com/elves/elvish/edit/prompt.makePrompt
        /build/go/src/github.com/elves/elvish/edit/prompt/prompt.go:69 +0x18f

execing recovery shell /bin/sh
```

**Comment by yrkv** [comment]
Elvish still looks at `edit:insert:binding["Ctrl-N"]` because it isn't bound in `edit:navigation:binding`

Seems like the real bug isn't the keybindings, but rather that calling `edit:navigation:start` when it's already in navigation mode crashes elvish. This is pretty easily solved by binding `Ctrl-N` to something when in navigation mode, such as `$nop~` to do nothing or `$edit:insert:start~` the file navigator.

I suggest adding `edit:navigation:binding["Ctrl-N"] = $nop~` to your `rc.elv` as a fix. 

It could also be a good idea to try and get it added as a default binding.

**Comment by xiaq** [comment]
Closing as dup of #627.

@yrkv The real bug is that Elvish should never crash with a nil pointer dereference.
