### ISSUE TITLE
Pressing Ctrl+N twice results in a crash

### ISSUE THREAD

**Issue by shdown** [elves/elvish#773]
````
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/elves/elvish/sys.DumpStack(0xc42019e858, 0x1)
	/home/v/go/src/github.com/elves/elvish/sys/dumpstack.go:10 +0xa2
github.com/elves/elvish/program/shell.rescue()
	/home/v/go/src/github.com/elves/elvish/program/shell/shell.go:62 +0xc5
panic(0x892ee0, 0xbe0280)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
github.com/elves/elvish/eval.catch(0xc42019f710, 0xc420088240)
	/home/v/go/src/github.com/elves/elvish/eval/frame.go:210 +0x266
panic(0x892ee0, 0xbe0280)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
github.com/elves/elvish/edit/edcore.(*navigation).List(0xc4200ac640, 0x33, 0xc4200ac640, 0x7feadc18c148)
	/home/v/go/src/github.com/elves/elvish/edit/edcore/navigation.go:346 +0x80
github.com/elves/elvish/edit/edcore.(*editorRenderer).Render(0xc4201e1460, 0xc420188b90)
	/home/v/go/src/github.com/elves/elvish/edit/edcore/render.go:242 +0x10b4
github.com/elves/elvish/edit/ui.Render(0x98a800, 0xc4201e1460, 0xc7, 0x98b780)
	/home/v/go/src/github.com/elves/elvish/edit/ui/render.go:16 +0x10b
github.com/elves/elvish/edit/edcore.(*editor).refresh(0xc420218000, 0x980101, 0xc420228fc0, 0x0)
	/home/v/go/src/github.com/elves/elvish/edit/edcore/edit.go:268 +0x2db
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc420218000, 0x98a880, 0xc420228fc0, 0x0, 0x0, 0x0)
	/home/v/go/src/github.com/elves/elvish/edit/edcore/api.go:121 +0x27e
github.com/elves/elvish/edit/edcore.(*navigation).defaultFn(0xc4200ac640, 0xc420218000)
	/home/v/go/src/github.com/elves/elvish/edit/edcore/navigation.go:165 +0xbf
github.com/elves/elvish/edit/edcore.initNavigation.func4()
	/home/v/go/src/github.com/elves/elvish/edit/edcore/navigation.go:65 +0x33
reflect.Value.call(0x85daa0, 0xc42013f0a0, 0x13, 0x925f9b, 0x4, 0x0, 0x0, 0x0, 0x0, 0x85daa0, ...)
	/usr/lib/go-1.10/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x85daa0, 0xc42013f0a0, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4202f4496)
	/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
github.com/elves/elvish/eval.(*BuiltinFn).Call(0xc420229340, 0xc420088240, 0x0, 0x0, 0x0, 0xc42018a7b0, 0x9058e0, 0xc42019f6c8)
	/home/v/go/src/github.com/elves/elvish/eval/builtin_fn.go:221 +0x586
github.com/elves/elvish/eval.(*Frame).Call(0xc420088240, 0x98a880, 0xc420229340, 0x0, 0x0, 0x0, 0xc42018a7b0, 0x0, 0x0)
	/home/v/go/src/github.com/elves/elvish/eval/frame.go:163 +0xbb
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc420218000, 0x98a880, 0xc420229340, 0x0, 0x0, 0x0)
	/home/v/go/src/github.com/elves/elvish/edit/edcore/api.go:115 +0x257
github.com/elves/elvish/edit/edcore.(*editor).ReadLine(0xc420218000, 0x0, 0x0, 0x0, 0x0)
	/home/v/go/src/github.com/elves/elvish/edit/edcore/edit.go:500 +0x9af
github.com/elves/elvish/program/shell.interact.func1(0x8abb80, 0xc42000dcc0, 0xf, 0x0)
	/home/v/go/src/github.com/elves/elvish/program/shell/interact.go:51 +0x2f
github.com/elves/elvish/program/shell.interact(0xc4201e80c0, 0xc420192940, 0xf, 0x0)
	/home/v/go/src/github.com/elves/elvish/program/shell/interact.go:61 +0x284
github.com/elves/elvish/program/shell.(*Shell).Main(0xc4201870c0, 0xc42009a170, 0x0, 0x0, 0x0)
	/home/v/go/src/github.com/elves/elvish/program/shell/shell.go:50 +0x1af
github.com/elves/elvish/program.Main(0xc42009a170, 0x1, 0x1, 0x0)
	/home/v/go/src/github.com/elves/elvish/program/program.go:123 +0x180
main.main()
	/home/v/go/src/github.com/elves/elvish/main.go:14 +0x45

goroutine 35 [runnable]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.10/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/lib/go-1.10/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/lib/go-1.10/src/os/signal/signal_unix.go:28 +0x41

goroutine 19 [chan receive]:
github.com/elves/elvish/eval.init.13.func1()
	/home/v/go/src/github.com/elves/elvish/eval/port.go:49 +0x53
created by github.com/elves/elvish/eval.init.13
	/home/v/go/src/github.com/elves/elvish/eval/port.go:48 +0x49

goroutine 4 [select, locked to thread]:
runtime.gopark(0x94fb40, 0x0, 0x927f55, 0x6, 0x18, 0x1)
	/usr/lib/go-1.10/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc420041750, 0xc42020c0c0)
	/usr/lib/go-1.10/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/usr/lib/go-1.10/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1

goroutine 37 [chan receive]:
github.com/elves/elvish/program/shell.handleSignals.func1(0xc42020c000)
	/home/v/go/src/github.com/elves/elvish/program/shell/shell.go:72 +0xb8
created by github.com/elves/elvish/program/shell.handleSignals
	/home/v/go/src/github.com/elves/elvish/program/shell/shell.go:71 +0x7c

goroutine 40 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc420232000)
	/home/v/go/src/github.com/elves/elvish/edit/prompt/prompt.go:76 +0xd1
created by github.com/elves/elvish/edit/prompt.makePrompt
	/home/v/go/src/github.com/elves/elvish/edit/prompt/prompt.go:69 +0x1b4

goroutine 41 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc420232080)
	/home/v/go/src/github.com/elves/elvish/edit/prompt/prompt.go:76 +0xd1
created by github.com/elves/elvish/edit/prompt.makePrompt
	/home/v/go/src/github.com/elves/elvish/edit/prompt/prompt.go:69 +0x1b4

execing recovery shell /bin/sh
$
````

**Comment by SolitudeSF** [comment]
#627

**Comment by shdown** [comment]
Okay
