### ISSUE TITLE
Segmentation violation when using $nil

### ISSUE THREAD

**Issue by hanche** [elves/elvish#818]
With a freshly built `elvish` on commit 4811ae61, macOS 10.14.4:

```
⬥ ./elvish
⬥ put $nil
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x116c91c]

goroutine 915 [running]:
github.com/elves/elvish/eval.catch(0xc0005d7f58, 0xc0004daba0)
	/opt/pkg/gopkg/src/github.com/elves/elvish/eval/frame.go:210 +0x262
panic(0x1508e60, 0x1a05570)
	/opt/local/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/elves/elvish/eval/vals.ScanToGo(0x0, 0x0, 0x14c0260, 0xc00026a310, 0x14c0260, 0xc00026a310)
	/opt/pkg/gopkg/src/github.com/elves/elvish/eval/vals/conversion.go:61 +0x28c
github.com/elves/elvish/eval.(*BuiltinFn).Call(0xc00016b960, 0xc0004daba0, 0xc00026a2f0, 0x1, 0x1, 0xc0004fab70, 0x0, 0x1)
	/opt/pkg/gopkg/src/github.com/elves/elvish/eval/builtin_fn.go:193 +0x37c
github.com/elves/elvish/eval.(*formOp).invoke(0xc0004caea0, 0xc0004daba0, 0x0, 0x0)
	/opt/pkg/gopkg/src/github.com/elves/elvish/eval/compile_effect.go:346 +0x946
github.com/elves/elvish/eval.effectOp.exec(...)
	/opt/pkg/gopkg/src/github.com/elves/elvish/eval/op.go:26
github.com/elves/elvish/eval.(*Frame).eval(0xc0004daba0, 0x1658c60, 0xc0004caea0, 0x0, 0x8, 0x0, 0x0)
	/opt/pkg/gopkg/src/github.com/elves/elvish/eval/frame.go:149 +0x94
github.com/elves/elvish/eval.(*pipelineOp).invoke.func1(0xc0004daba0, 0x1658c60, 0xc0004caea0, 0x0, 0x8, 0xc0000101e0, 0xc0004d9790, 0xc0004daa00)
	/opt/pkg/gopkg/src/github.com/elves/elvish/eval/compile_effect.go:101 +0x60
created by github.com/elves/elvish/eval.(*pipelineOp).invoke
	/opt/pkg/gopkg/src/github.com/elves/elvish/eval/compile_effect.go:100 +0x242
Exception: ./elvish exited with 2
[tty], line 1: ./elvish
```

**Comment by zzamboni** [comment]
It's not only functions, also simple assignment triggers a crash:
```
[~]─> a=$nil
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x116c8fc]

goroutine 21105 [running]:
github.com/elves/elvish/eval.catch(0xc000ad3f58, 0xc000b78720)
	/Users/taazadi1/Dropbox/Personal/devel/go/src/github.com/elves/elvish/eval/frame.go:210 +0x262
panic(0x1508dc0, 0x1a09570)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:522 +0x1b5
github.com/elves/elvish/eval/vals.ScanToGo(0x0, 0x0, 0x14c01c0, 0xc000832f00, 0x1417a58, 0x1a37400)
	/Users/taazadi1/Dropbox/Personal/devel/go/src/github.com/elves/elvish/eval/vals/conversion.go:61 +0x28c
github.com/elves/elvish/eval/vars.ptrVariable.Set(0x14c01c0, 0xc000832f00, 0xc0003b8480, 0x0, 0x0, 0x0, 0x0)
	/Users/taazadi1/Dropbox/Personal/devel/go/src/github.com/elves/elvish/eval/vars/ptr.go:46 +0x89
github.com/elves/elvish/eval.(*assignmentOp).invoke(0xc000b785a0, 0xc000b78720, 0x0, 0x0)
	/Users/taazadi1/Dropbox/Personal/devel/go/src/github.com/elves/elvish/eval/compile_effect.go:416 +0x2c4
github.com/elves/elvish/eval.effectOp.exec(...)
	/Users/taazadi1/Dropbox/Personal/devel/go/src/github.com/elves/elvish/eval/op.go:26
github.com/elves/elvish/eval.seqOp.invoke(0xc0003c7a80, 0x1, 0x1, 0xc000b78720, 0x10, 0xc000818ee0)
	/Users/taazadi1/Dropbox/Personal/devel/go/src/github.com/elves/elvish/eval/compile_effect.go:575 +0x79
github.com/elves/elvish/eval.effectOp.exec(...)
	/Users/taazadi1/Dropbox/Personal/devel/go/src/github.com/elves/elvish/eval/op.go:26
github.com/elves/elvish/eval.(*Frame).eval(0xc000b78720, 0x1659ca0, 0xc0003c7b00, 0x0, 0x6, 0x0, 0x0)
	/Users/taazadi1/Dropbox/Personal/devel/go/src/github.com/elves/elvish/eval/frame.go:149 +0x94
github.com/elves/elvish/eval.(*pipelineOp).invoke.func1(0xc000b78720, 0x1659ca0, 0xc0003c7b00, 0x0, 0x6, 0xc000c06370, 0xc000826730, 0xc000b78600)
	/Users/taazadi1/Dropbox/Personal/devel/go/src/github.com/elves/elvish/eval/compile_effect.go:101 +0x60
created by github.com/elves/elvish/eval.(*pipelineOp).invoke
	/Users/taazadi1/Dropbox/Personal/devel/go/src/github.com/elves/elvish/eval/compile_effect.go:100 +0x242
```
