### ISSUE TITLE
Panic when using $nil as a key

### ISSUE THREAD

**Issue by hanche** [elves/elvish#835]
Using `$nil` as a key in a map leads to a panic when accessed:

```
⬥ elvish
⬥ xx = [&]
⬥ xx[$nil] = foo
⬥ put $xx
▶ panic: interface conversion: string is not hashmap.node: missing method assoc

goroutine 924 [running]:
github.com/elves/elvish/vendor/github.com/xiaq/persistent/hashmap.(*bitmapNodeIterator).fixCurrent(0xc00051c880)
	/opt/pkg/gopkg/src/github.com/elves/elvish/vendor/github.com/xiaq/persistent/hashmap/hashmap.go:437 +0xa5
github.com/elves/elvish/vendor/github.com/xiaq/persistent/hashmap.(*bitmapNode).iterator(0xc0002dda40, 0xc000267d01, 0x166b5c0)
	/opt/pkg/gopkg/src/github.com/elves/elvish/vendor/github.com/xiaq/persistent/hashmap/hashmap.go:423 +0x6d
github.com/elves/elvish/vendor/github.com/xiaq/persistent/hashmap.(*hashMap).Iterator(0xc0002d2c90, 0x1544940, 0xc0002d2c90)
	/opt/pkg/gopkg/src/github.com/elves/elvish/vendor/github.com/xiaq/persistent/hashmap/hashmap.go:65 +0x34
github.com/elves/elvish/eval/vals.Repr(0x1544940, 0xc0002d2c90, 0x8000000000000000, 0x20, 0x4)
	/opt/pkg/gopkg/src/github.com/elves/elvish/eval/vals/repr.go:57 +0x288
github.com/elves/elvish/eval.relayChanToFile(0xc0002ce120, 0xc000010010, 0x15a1074, 0x4, 0xc000430074)
	/opt/pkg/gopkg/src/github.com/elves/elvish/eval/std_ports.go:42 +0xec
created by github.com/elves/elvish/eval.newStdPorts
	/opt/pkg/gopkg/src/github.com/elves/elvish/eval/std_ports.go:26 +0xf9
Exception: elvish exited with 2
[tty], line 1: elvish
```

**Comment by doubleagent** [comment]
I get "Compilation error: variable $nil not found".  What version and system are you running this on?

**Comment by SolitudeSF** [comment]
@doubleagent, you are probably using the stable version. it crashes on master.

**Comment by xiaq** [comment]
Aha. This is not surprising. I have not implemented support for nil keys in the hash map module...
