### ISSUE TITLE
runtime error: invalid memory address... When hitting Ctrl+N twice

### ISSUE THREAD

**Issue by epikur-io** [elves/elvish#877]
I think the title says pretty much everything.
This is my stack track / console output:

```
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/elves/elvish/sys.DumpStack(0xa8ccc0, 0xc000010018)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/sys/dumpstack.go:10 +0x9d
github.com/elves/elvish/program/shell.rescue()
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/program/shell/shell.go:71 +0xd1
panic(0x929a40, 0xe12540)
	/home/epikur/go/src/runtime/panic.go:679 +0x1b2
github.com/elves/elvish/eval.catch(0xc0003016c0, 0xc000218cc0)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/eval/frame.go:210 +0x25f
panic(0x929a40, 0xe12540)
	/home/epikur/go/src/runtime/panic.go:679 +0x1b2
github.com/elves/elvish/edit/edcore.(*navigation).List(0xc0001447d0, 0x1c, 0xc0001447d0, 0x7fc1d39f6ee8)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/edcore/navigation.go:346 +0x80
github.com/elves/elvish/edit/edcore.(*editorRenderer).Render(0xc0002287e0, 0xc00027c1e0)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/edcore/render.go:242 +0x1038
github.com/elves/elvish/edit/ui.Render(0xa8c440, 0xc0002287e0, 0xee, 0xc00010c7b0)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/ui/render.go:20 +0xe9
github.com/elves/elvish/edit/edcore.(*editor).refresh(0xc0001b4000, 0xa80101, 0xc0001c1500, 0x0)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/edcore/edit.go:268 +0x4a3
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc0001b4000, 0xa8c500, 0xc0001c1500, 0x0, 0x0, 0x0)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/edcore/api.go:121 +0x24c
github.com/elves/elvish/edit/edcore.(*navigation).defaultFn(0xc0001447d0, 0xc0001b4000)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/edcore/navigation.go:165 +0x136
github.com/elves/elvish/edit/edcore.initNavigation.func4()
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/edcore/navigation.go:65 +0x33
reflect.Value.call(0x8efd20, 0xc00017ff80, 0x13, 0x9cb387, 0x4, 0x0, 0x0, 0x0, 0xc0000980c0, 0xc00002e6c0, ...)
	/home/epikur/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x8efd20, 0xc00017ff80, 0x13, 0x0, 0x0, 0x0, 0x0, 0xc000301820, 0xc0000980c0)
	/home/epikur/go/src/reflect/value.go:321 +0xb4
github.com/elves/elvish/eval.(*GoFn).Call(0xc0001c0f50, 0xc000218cc0, 0x0, 0x0, 0x0, 0xc00010c2d0, 0x0, 0x40ae2b)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/eval/go_fn.go:227 +0x638
github.com/elves/elvish/eval.(*Frame).Call(0xc000218cc0, 0xa8c500, 0xc0001c0f50, 0x0, 0x0, 0x0, 0xc00010c2d0, 0x0, 0x0)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/eval/frame.go:163 +0xdf
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc0001b4000, 0xa8c500, 0xc0001c0f50, 0x0, 0x0, 0x0)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/edcore/api.go:115 +0x225
github.com/elves/elvish/edit/edcore.(*editor).ReadLine(0xc0001b4000, 0x0, 0x0, 0x0, 0x0)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/edcore/edit.go:500 +0x1125
github.com/elves/elvish/program/shell.interact(0xc000186000, 0xc000141140, 0x14, 0x0)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/program/shell/interact.go:62 +0x2fc
github.com/elves/elvish/program/shell.(*Shell).Main(0xc000130880, 0xc0000201b0, 0x0, 0x0, 0x0)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/program/shell/shell.go:59 +0x301
github.com/elves/elvish/program.Main(0xc0000201b0, 0x1, 0x1, 0x0)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/program/program.go:123 +0x196
main.main()
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/main.go:14 +0x45

goroutine 18 [syscall]:
os/signal.signal_recv(0xa935a0)
	/home/epikur/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/home/epikur/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/home/epikur/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 19 [chan receive]:
github.com/elves/elvish/eval.init.13.func1()
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/eval/port.go:49 +0x53
created by github.com/elves/elvish/eval.init.13
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/eval/port.go:48 +0x49

goroutine 22 [chan receive]:
github.com/elves/elvish/program/shell.handleSignals.func1(0xc0001500c0)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/program/shell/shell.go:81 +0xb8
created by github.com/elves/elvish/program/shell.handleSignals
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/program/shell/shell.go:80 +0x7c

goroutine 24 [runnable]:
github.com/elves/elvish/edit/edcore.NewEditor.func2(0xc0001503c0, 0xc0001b4000)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/edcore/edit.go:132 +0xea
created by github.com/elves/elvish/edit/edcore.NewEditor
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/edcore/edit.go:131 +0x2c7

goroutine 25 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc000170480)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/prompt/prompt.go:76 +0xd1
created by github.com/elves/elvish/edit/prompt.makePrompt
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/prompt/prompt.go:69 +0x18f

goroutine 26 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc000170500)
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/prompt/prompt.go:76 +0xd1
created by github.com/elves/elvish/edit/prompt.makePrompt
	/var/users/epikur/go/site-packages/src/github.com/elves/elvish/edit/prompt/prompt.go:69 +0x18f

execing recovery shell /bin/sh
```

Probably the Key event should be prevented to trigger twice in this and similar cases.

Edit: This seems to be fixed in v0.10.2-0.20191214164217-9b4add3b4e3b.
But now my promt isn't working anymore because of a api change:
` prompt function error: variable $edit:styled~ not found`

Whats the new api for changing the promt?

**Comment by SolitudeSF** [comment]
use `styled`

**Comment by xiaq** [comment]
This has been fixed in HEAD.
